import { ProjectConfig } from "@/types/project";

export interface GeneratedFile {
  path: string;
  content: string;
  category: "sql" | "functions" | "frontend" | "docs";
}

// ─── Orchestrator ────────────────────────────────────────────────────────────

// Helper: Get the admin role name (first role that contains 'admin' or 'owner', or the first role)
function getAdminRoleName(config: ProjectConfig): string | null {
  if (config.roles.length === 0) return null;
  const adminRole = config.roles.find(r => 
    r.name.toLowerCase().includes('admin') || 
    r.name.toLowerCase().includes('owner')
  );
  return adminRole ? adminRole.name : config.roles[0].name;
}

export function generateProject(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // 1. Core schema
  files.push({ path: "migrations/001_core.sql", content: generateCoreSchema(config), category: "sql" });

  // 2. Roles setup (if roles defined)
  if (config.roles.length > 0) {
    files.push({ path: "migrations/002_roles.sql", content: generateRolesSetup(config), category: "sql" });
  }

  // 3. RLS policies — ALWAYS generated (owner-based baseline + role-based if roles exist)
  files.push({ path: `migrations/${config.roles.length > 0 ? '003' : '002'}_rls.sql`, content: generateRLS(config), category: "sql" });

  // 3. Optional modules — each gets its own numbered migration
  let migrationIdx = 4;
  const optionalModules: { flag: keyof typeof config.features; fn: (c: ProjectConfig) => GeneratedFile[] }[] = [
    { flag: "auditLogs", fn: generateAuditLogModule },
    { flag: "softDelete", fn: generateSoftDeleteModule },
    { flag: "fileUploads", fn: generateStorageModule },
    { flag: "rateLimiting", fn: generateRateLimitingModule },
    { flag: "multiTenancy", fn: generateMultiTenancyModule },
    { flag: "logging", fn: generateLoggingModule },
    { flag: "featureFlags", fn: generateFeatureFlagsModule },
    { flag: "backgroundJobs", fn: generateBackgroundJobsModule },
  ];

  for (const mod of optionalModules) {
    if (config.features[mod.flag]) {
      const moduleFiles = mod.fn(config);
      // Prefix SQL files with migration index
      for (const f of moduleFiles) {
        if (f.category === "sql" && f.path.startsWith("migrations/")) {
          f.path = `migrations/${String(migrationIdx).padStart(3, "0")}_${f.path.replace("migrations/", "")}`;
          migrationIdx++;
        }
        files.push(f);
      }
    }
  }

  // 4. Seed data
  files.push({ path: "seed.sql", content: generateSeed(config), category: "sql" });

  // 5. Edge functions
  config.apiEndpoints.filter((e) => e.crud).forEach((ep) => {
    files.push({
      path: `functions/${ep.table}/index.ts`,
      content: generateEdgeFunction(ep.table, config),
      category: "functions",
    });
  });

  // 6. API Integration Framework
  if (config.features.apiIntegrations) {
    files.push(...generateIntegrationFramework());
  }

  // 7. Frontend (optional)
  if (config.frontendOptions.enabled) {
    files.push(...generateFrontendFiles(config));
  }

  // 8. Documentation
  files.push({ path: "README.md", content: generateReadme(config), category: "docs" });
  files.push({ path: "API.md", content: generateApiDocs(config), category: "docs" });
  files.push({ path: "ARCHITECTURE.md", content: generateArchitectureDocs(config), category: "docs" });
  files.push({ path: ".env.example", content: generateEnvExample(config), category: "docs" });

  return files;
}

// ─── Core Schema ─────────────────────────────────────────────────────────────

function generateCoreSchema(config: ProjectConfig): string {
  const lines: string[] = [
    "-- ============================================================",
    "-- Generated by Supabase Project Factory",
    `-- Project: ${config.projectName}`,
    "-- ",
    "-- SECURITY: All tables have RLS enabled by default.",
    "-- Without explicit policies, no access is granted (deny-all).",
    "-- ============================================================",
    "",
  ];

  // ── Multi-tenancy: organizations & org_members MUST come first ──────────
  if (config.features.multiTenancy) {
    lines.push("-- ── Organizations (multi-tenancy core) ──────────────────────");
    lines.push(`CREATE TABLE public.organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  settings JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);`);
    lines.push("");
    lines.push("ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;");
    lines.push("");

    lines.push(`CREATE TABLE public.organization_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  organization_id UUID REFERENCES public.organizations(id) ON DELETE CASCADE NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, organization_id)
);`);
    lines.push("");
    lines.push("ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;");
    lines.push("");

    // Auto-create org trigger
    lines.push(`-- Auto-create a "Home Organization" for every new user on signup
CREATE OR REPLACE FUNCTION public.handle_new_user_org()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  new_org_id UUID;
BEGIN
  INSERT INTO public.organizations (name, slug, owner_id)
  VALUES ('My Organization', 'org-' || LEFT(NEW.id::TEXT, 8), NEW.id)
  RETURNING id INTO new_org_id;

  INSERT INTO public.organization_members (user_id, organization_id, role)
  VALUES (NEW.id, new_org_id, 'admin');

  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created_org
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_org();`);
    lines.push("");
  }

  // ── User-defined tables ────────────────────────────────────────────────────
  for (const table of config.tables) {
    if (!table.name) continue;

    lines.push(`-- ── Table: ${table.name} ──────────────────────────────────`);
    lines.push(`CREATE TABLE public.${table.name} (`);
    const colDefs: string[] = [];

    for (const col of table.columns) {
      if (!col.name) continue;
      let def = `  ${col.name} ${col.type.toUpperCase()}`;
      if (col.isPrimary) def += " PRIMARY KEY";
      if (col.type === "uuid" && col.isPrimary) def += " DEFAULT gen_random_uuid()";
      if (col.isRequired && !col.isPrimary) def += " NOT NULL";
      if (col.isUnique && !col.isPrimary) def += " UNIQUE";
      if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
      if (col.references) {
        def += ` REFERENCES ${col.references.table}(${col.references.column}) ON DELETE CASCADE`;
      }
      colDefs.push(def);
    }

    if (config.features.auth && !table.columns.some((c) => c.name === "user_id")) {
      colDefs.push("  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL");
    }

    if (config.features.timestamps) {
      if (!table.columns.some((c) => c.name === "created_at"))
        colDefs.push("  created_at TIMESTAMPTZ NOT NULL DEFAULT now()");
      if (!table.columns.some((c) => c.name === "updated_at"))
        colDefs.push("  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()");
    }

    if (config.features.softDelete) {
      colDefs.push("  deleted_at TIMESTAMPTZ");
    }

    if (config.features.multiTenancy) {
      if (!table.columns.some((c) => c.name === "organization_id")) {
        colDefs.push("  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE");
      }
    }

    lines.push(colDefs.join(",\n"));
    lines.push(");");
    lines.push("");

    // Indexes
    for (const col of table.columns) {
      if (col.isIndexed && !col.isPrimary) {
        lines.push(`CREATE INDEX idx_${table.name}_${col.name} ON public.${table.name}(${col.name});`);
      }
    }

    if (config.features.multiTenancy) {
      lines.push(`CREATE INDEX idx_${table.name}_org ON public.${table.name}(organization_id);`);
    }

    // RLS — secure by default
    lines.push(`-- SECURITY: RLS enabled. Without policies, all access is denied.`);
    lines.push(`ALTER TABLE public.${table.name} ENABLE ROW LEVEL SECURITY;`);
    lines.push("");
  }

  // Foreign keys for 1:1 and 1:N relationships
  for (const rel of config.relationships) {
    if (rel.type === "1:1" || rel.type === "1:N") {
      const toTable = config.tables.find(t => t.name === rel.to.table);
      const fkColumnName = `${rel.from.table}_id`;
      const columnExists = toTable?.columns.some(c => c.name === fkColumnName || c.name === rel.to.column);
      
      if (!columnExists) {
        lines.push(
          `ALTER TABLE public.${rel.to.table} ADD COLUMN ${fkColumnName} UUID REFERENCES public.${rel.from.table}(id) ON DELETE CASCADE;`
        );
      }
    } else if (rel.type === "N:N") {
      const jt = `${rel.from.table}_${rel.to.table}`;
      lines.push(`-- Junction table for N:N relationship`);
      lines.push(`CREATE TABLE public.${jt} (`);
      lines.push(`  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),`);
      lines.push(`  ${rel.from.table}_id UUID REFERENCES public.${rel.from.table}(id) ON DELETE CASCADE NOT NULL,`);
      lines.push(`  ${rel.to.table}_id UUID REFERENCES public.${rel.to.table}(id) ON DELETE CASCADE NOT NULL,`);
      lines.push(`  UNIQUE(${rel.from.table}_id, ${rel.to.table}_id)`);
      lines.push(`);`);
      lines.push(`ALTER TABLE public.${jt} ENABLE ROW LEVEL SECURITY;`);
      lines.push("");
    }
  }

  // Timestamp trigger
  if (config.features.timestamps) {
    lines.push(`
-- Auto-update updated_at on row changes
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
`);
    for (const table of config.tables) {
      if (!table.name) continue;
      lines.push(
        `CREATE TRIGGER update_${table.name}_updated_at BEFORE UPDATE ON public.${table.name} FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();`
      );
    }
  }

  return lines.join("\n");
}

// ─── Roles Setup ─────────────────────────────────────────────────────────────

function generateRolesSetup(config: ProjectConfig): string {
  const roleNames = config.roles.map((r) => `'${r.name}'`).join(", ");
  const adminRole = getAdminRoleName(config) || config.roles[0]?.name || 'admin';
  return `-- ============================================================
-- Role-Based Access Control Setup
-- SECURITY: Roles are stored in a separate table (not on profiles)
-- to prevent privilege escalation attacks.
-- ============================================================

CREATE TYPE public.app_role AS ENUM (${roleNames});

CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  UNIQUE (user_id, role)
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Security definer function to check roles (avoids RLS recursion)
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

-- Security definer function to get user's role (avoids RLS recursion)
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT role::TEXT FROM public.user_roles
  WHERE user_id = auth.uid()
  LIMIT 1
$$;

${config.features.multiTenancy ? `
-- Helper: Check if the current user is a member of the given org (stub for multi-tenancy)
-- Full implementation is in the multi-tenancy migration
CREATE OR REPLACE FUNCTION public.is_tenant_member(_org_id UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT false -- Will be replaced by multi-tenancy migration
$$;
` : ''}

-- Users can read their own roles
CREATE POLICY "Users can view own roles"
  ON public.user_roles FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Only admins can manage roles
CREATE POLICY "Admins can manage roles"
  ON public.user_roles FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));

-- BOOTSTRAP: Allow first admin to self-assign when no admins exist yet.
-- Once an admin exists, this policy stops granting access.
CREATE POLICY "Bootstrap first admin"
  ON public.user_roles FOR INSERT
  TO authenticated
  WITH CHECK (
    auth.uid() = user_id
    AND NOT EXISTS (SELECT 1 FROM public.user_roles WHERE role = '${adminRole}')
  );
`;
}

// ─── RLS Policies ────────────────────────────────────────────────────────────

function generateRLS(config: ProjectConfig): string {
  const lines: string[] = [
    "-- ============================================================",
    "-- Row Level Security Policies",
    "-- ============================================================",
    "",
  ];

  const hasRoles = config.roles.length > 0;

  // ── Role-based policies (only if roles exist) ─────────────────────────────
  if (hasRoles) {
    lines.push("-- ── Role-based policies ──────────────────────────────────────");
    lines.push("-- Uses has_role() security definer function to avoid recursive RLS.");
    lines.push("");

    for (const role of config.roles) {
      if (!role.name) continue;
      for (const table of config.tables) {
        if (!table.name) continue;
        const perms = role.permissions[table.name];
        if (!perms) continue;

        const tenantClause = config.features.multiTenancy
          ? " OR public.is_tenant_member(organization_id)"
          : "";

        if (perms.select) {
          lines.push(`CREATE POLICY "${role.name}_select_${table.name}"`);
          lines.push(`  ON public.${table.name} FOR SELECT TO authenticated`);
          lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${tenantClause});`);
          lines.push("");
        }
        if (perms.insert) {
          lines.push(`CREATE POLICY "${role.name}_insert_${table.name}"`);
          lines.push(`  ON public.${table.name} FOR INSERT TO authenticated`);
          lines.push(`  WITH CHECK (public.has_role(auth.uid(), '${role.name}')${tenantClause});`);
          lines.push("");
        }
        if (perms.update) {
          lines.push(`CREATE POLICY "${role.name}_update_${table.name}"`);
          lines.push(`  ON public.${table.name} FOR UPDATE TO authenticated`);
          lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${tenantClause});`);
          lines.push("");
        }
        if (perms.delete) {
          lines.push(`CREATE POLICY "${role.name}_delete_${table.name}"`);
          lines.push(`  ON public.${table.name} FOR DELETE TO authenticated`);
          lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${tenantClause});`);
          lines.push("");
        }
      }
    }
  }

  // ── Owner-based baseline policies ──────────────────────────────────────────
  // These ensure authenticated users can always manage their OWN records
  lines.push("-- ── Owner-based baseline policies ────────────────────────────");
  lines.push("-- Ensures users can always manage their own records (via user_id).");
  lines.push("");

  for (const table of config.tables) {
    if (!table.name) continue;
    const hasUserId = config.features.auth || table.columns.some(c => c.name === "user_id");
    if (!hasUserId) continue;

    lines.push(`CREATE POLICY "owner_select_${table.name}"`);
    lines.push(`  ON public.${table.name} FOR SELECT TO authenticated`);
    lines.push(`  USING (auth.uid() = user_id);`);
    lines.push("");

    lines.push(`CREATE POLICY "owner_insert_${table.name}"`);
    lines.push(`  ON public.${table.name} FOR INSERT TO authenticated`);
    lines.push(`  WITH CHECK (auth.uid() = user_id);`);
    lines.push("");

    lines.push(`CREATE POLICY "owner_update_${table.name}"`);
    lines.push(`  ON public.${table.name} FOR UPDATE TO authenticated`);
    lines.push(`  USING (auth.uid() = user_id);`);
    lines.push("");

    lines.push(`CREATE POLICY "owner_delete_${table.name}"`);
    lines.push(`  ON public.${table.name} FOR DELETE TO authenticated`);
    lines.push(`  USING (auth.uid() = user_id);`);
    lines.push("");
  }

  // ── Multi-tenancy RLS for user tables (if no roles) ────────────────────────
  if (config.features.multiTenancy && !hasRoles) {
    lines.push("-- ── Tenant-scoped policies ───────────────────────────────────");
    lines.push("");
    for (const table of config.tables) {
      if (!table.name) continue;
      lines.push(`CREATE POLICY "tenant_select_${table.name}"`);
      lines.push(`  ON public.${table.name} FOR SELECT TO authenticated`);
      lines.push(`  USING (public.is_tenant_member(organization_id));`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

// ─── Module: Audit Logs ──────────────────────────────────────────────────────

function generateAuditLogModule(config: ProjectConfig): GeneratedFile[] {
  const adminRole = getAdminRoleName(config);
  let sql = `-- ============================================================
-- Module: Audit Logging
-- Tracks all INSERT/UPDATE/DELETE operations on user tables.
-- SECURITY: Only admins can read audit logs.
-- ============================================================

CREATE TABLE public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name TEXT NOT NULL,
  record_id TEXT,
  action TEXT NOT NULL,
  old_data JSONB,
  new_data JSONB,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_audit_logs_created_at ON public.audit_logs(created_at);
CREATE INDEX idx_audit_logs_table_name ON public.audit_logs(table_name);

${adminRole ? `CREATE POLICY "Admins can view audit logs"
  ON public.audit_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));` : '-- No admin role defined, audit logs are service-role only'}

CREATE OR REPLACE FUNCTION public.audit_trigger_fn()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, old_data, user_id)
    VALUES (TG_TABLE_NAME, OLD.id::TEXT, 'DELETE', to_jsonb(OLD), auth.uid());
    RETURN OLD;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, old_data, new_data, user_id)
    VALUES (TG_TABLE_NAME, NEW.id::TEXT, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), auth.uid());
    RETURN NEW;
  ELSIF TG_OP = 'INSERT' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, new_data, user_id)
    VALUES (TG_TABLE_NAME, NEW.id::TEXT, 'INSERT', to_jsonb(NEW), auth.uid());
    RETURN NEW;
  END IF;
END;
$$;
`;

  for (const table of config.tables) {
    if (!table.name) continue;
    sql += `\nCREATE TRIGGER audit_${table.name} AFTER INSERT OR UPDATE OR DELETE ON public.${table.name} FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_fn();`;
  }

  return [{ path: "migrations/audit.sql", content: sql, category: "sql" }];
}

// ─── Module: Soft Delete ─────────────────────────────────────────────────────

function generateSoftDeleteModule(config: ProjectConfig): GeneratedFile[] {
  const lines: string[] = [
    "-- ============================================================",
    "-- Module: Soft Delete",
    "-- Creates filtered views showing only non-deleted records.",
    "-- ============================================================",
    "",
  ];
  for (const table of config.tables) {
    if (!table.name) continue;
    lines.push(`CREATE VIEW public.${table.name}_active AS SELECT * FROM public.${table.name} WHERE deleted_at IS NULL;`);
  }
  return [{ path: "migrations/soft_delete.sql", content: lines.join("\n"), category: "sql" }];
}

// ─── Module: Storage ─────────────────────────────────────────────────────────

function generateStorageModule(_config: ProjectConfig): GeneratedFile[] {
  return [{
    path: "migrations/storage.sql",
    content: `-- ============================================================
-- Module: File Storage
-- SECURITY: Users can only access files in their own folder.
-- ============================================================

INSERT INTO storage.buckets (id, name, public) VALUES ('uploads', 'uploads', false);

CREATE POLICY "Users can upload files"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);

CREATE POLICY "Users can view own files"
  ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete own files"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);
`,
    category: "sql",
  }];
}

// ─── Module: Rate Limiting ───────────────────────────────────────────────────

function generateRateLimitingModule(config: ProjectConfig): GeneratedFile[] {
  const adminRole = getAdminRoleName(config);
  const sql = `-- ============================================================
-- Module: Rate Limiting
-- SECURITY: Admin-only management of rate limit rules.
-- Users can only view their own request logs.
-- ============================================================

CREATE TABLE public.api_rate_limits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  endpoint TEXT NOT NULL,
  max_requests INT NOT NULL DEFAULT 100,
  window_seconds INT NOT NULL DEFAULT 60,
  role TEXT DEFAULT 'authenticated',
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;

-- SECURITY: Only admins can configure rate limits
${adminRole ? `CREATE POLICY "Admins can manage rate limits"
  ON public.api_rate_limits FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));` : '-- No admin role defined, rate limits are service-role only'}

CREATE POLICY "Authenticated can read rate limits"
  ON public.api_rate_limits FOR SELECT TO authenticated
  USING (true);

CREATE TABLE public.request_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  endpoint TEXT NOT NULL,
  ip_address INET,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.request_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_request_logs_endpoint_created ON public.request_logs(endpoint, created_at);
CREATE INDEX idx_request_logs_ip_created ON public.request_logs(ip_address, created_at);
CREATE INDEX idx_request_logs_user_created ON public.request_logs(user_id, created_at);

-- SECURITY: Users can only see their own request logs
CREATE POLICY "Users can view own request logs"
  ON public.request_logs FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

${adminRole ? `CREATE POLICY "Admins can view all request logs"
  ON public.request_logs FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));` : ''}

-- Service role inserts request logs (from edge function)
CREATE POLICY "Service can insert request logs"
  ON public.request_logs FOR INSERT TO service_role
  WITH CHECK (true);

-- Cleanup function for old request logs
CREATE OR REPLACE FUNCTION public.cleanup_request_logs(retention_hours INT DEFAULT 24)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  DELETE FROM public.request_logs
  WHERE created_at < now() - (retention_hours || ' hours')::INTERVAL;
END;
$$;
`;

  const edgeFn = `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  try {
    const { endpoint, user_id, ip_address } = await req.json()

    const { data: limitConfig } = await supabase
      .from('api_rate_limits')
      .select('*')
      .eq('endpoint', endpoint)
      .single()

    const maxRequests = limitConfig?.max_requests ?? 100
    const windowSeconds = limitConfig?.window_seconds ?? 60
    const windowStart = new Date(Date.now() - windowSeconds * 1000).toISOString()

    let query = supabase
      .from('request_logs')
      .select('id', { count: 'exact' })
      .eq('endpoint', endpoint)
      .gte('created_at', windowStart)

    if (user_id) {
      query = query.eq('user_id', user_id)
    } else if (ip_address) {
      query = query.eq('ip_address', ip_address)
    }

    const { count } = await query

    await supabase.from('request_logs').insert({
      endpoint,
      user_id: user_id || null,
      ip_address: ip_address || null,
    })

    if ((count ?? 0) >= maxRequests) {
      return new Response(
        JSON.stringify({ error: 'Rate limit exceeded', retry_after: windowSeconds }),
        {
          status: 429,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json',
            'Retry-After': String(windowSeconds),
          },
        }
      )
    }

    return new Response(
      JSON.stringify({ allowed: true, remaining: maxRequests - (count ?? 0) - 1 }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
`;

  return [
    { path: "migrations/rate_limiting.sql", content: sql, category: "sql" },
    { path: "functions/rate-limiter/index.ts", content: edgeFn, category: "functions" },
  ];
}

// ─── Module: Multi-Tenancy ───────────────────────────────────────────────────
// NOTE: Table creation (organizations, organization_members) and the auto-org
// trigger are now in generateCoreSchema. This module only adds helper functions,
// RLS policies, and FK constraints.

function generateMultiTenancyModule(config: ProjectConfig): GeneratedFile[] {
  let sql = `-- ============================================================
-- Module: Multi-Tenancy (helpers, RLS policies, FK constraints)
-- Tables & trigger are created in 001_core.sql.
-- ============================================================

-- Helper: Check if the current user is a member of the given org
-- This replaces the stub created in the roles migration
CREATE OR REPLACE FUNCTION public.is_tenant_member(_org_id UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.organization_members
    WHERE user_id = auth.uid() AND organization_id = _org_id
  )
$$;

-- Helper: Get the user's current organization (first org they belong to)
CREATE OR REPLACE FUNCTION public.current_organization()
RETURNS UUID LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT organization_id FROM public.organization_members
  WHERE user_id = auth.uid()
  LIMIT 1
$$;

-- RLS: Members can see their own organizations
CREATE POLICY "Members can view own orgs"
  ON public.organizations FOR SELECT TO authenticated
  USING (public.is_tenant_member(id));

-- RLS: Owners can manage their orgs
CREATE POLICY "Owners can manage orgs"
  ON public.organizations FOR ALL TO authenticated
  USING (owner_id = auth.uid());

-- RLS: Members can see their own memberships
CREATE POLICY "Members can view own memberships"
  ON public.organization_members FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- RLS: Org admins can manage members
CREATE POLICY "Org admins can manage members"
  ON public.organization_members FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.organization_members om
      WHERE om.user_id = auth.uid()
        AND om.organization_id = organization_id
        AND om.role = 'admin'
    )
  );
`;

  return [{ path: "migrations/multi_tenancy.sql", content: sql, category: "sql" }];
}

// ─── Module: Centralized Logging ─────────────────────────────────────────────

function generateLoggingModule(config: ProjectConfig): GeneratedFile[] {
  const adminRole = getAdminRoleName(config);
  const sql = `-- ============================================================
-- Module: Centralized Logging & Analytics
-- SECURITY: Error logs and API metrics are admin-only.
-- Users can view their own activity logs.
-- ============================================================

CREATE TABLE public.activity_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_activity_logs_created_at ON public.activity_logs(created_at);
CREATE INDEX idx_activity_logs_user_id ON public.activity_logs(user_id);

CREATE POLICY "Users can view own activity"
  ON public.activity_logs FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

${adminRole ? `CREATE POLICY "Admins can view all activity"
  ON public.activity_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));` : ''}

CREATE POLICY "Service can insert activity"
  ON public.activity_logs FOR INSERT TO service_role
  WITH CHECK (true);

CREATE TABLE public.error_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  error_type TEXT NOT NULL,
  message TEXT NOT NULL,
  stack_trace TEXT,
  context JSONB DEFAULT '{}',
  severity TEXT NOT NULL DEFAULT 'error',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_error_logs_created_at ON public.error_logs(created_at);
CREATE INDEX idx_error_logs_severity ON public.error_logs(severity);

${adminRole ? `CREATE POLICY "Admins can view error logs"
  ON public.error_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));` : '-- No admin role defined, error logs are service-role only'}

CREATE POLICY "Service can insert error logs"
  ON public.error_logs FOR INSERT TO service_role
  WITH CHECK (true);

CREATE TABLE public.api_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  endpoint TEXT NOT NULL,
  method TEXT NOT NULL,
  status_code INT NOT NULL,
  duration_ms INT NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.api_metrics ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_api_metrics_created_at ON public.api_metrics(created_at);
CREATE INDEX idx_api_metrics_endpoint ON public.api_metrics(endpoint);

${adminRole ? `CREATE POLICY "Admins can view api metrics"
  ON public.api_metrics FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));` : '-- No admin role defined, API metrics are service-role only'}

CREATE POLICY "Service can insert api metrics"
  ON public.api_metrics FOR INSERT TO service_role
  WITH CHECK (true);
`;

  const edgeFn = `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  try {
    const { endpoint, method, status_code, duration_ms, user_id, action, resource_type, resource_id, metadata, error_type, message, stack_trace, severity } = await req.json()

    if (endpoint && status_code) {
      await supabase.from('api_metrics').insert({
        endpoint,
        method: method || 'GET',
        status_code,
        duration_ms: duration_ms || 0,
        user_id: user_id || null,
      })
    }

    if (action) {
      await supabase.from('activity_logs').insert({
        user_id: user_id || null,
        action,
        resource_type: resource_type || null,
        resource_id: resource_id || null,
        metadata: metadata || {},
      })
    }

    if (error_type) {
      await supabase.from('error_logs').insert({
        error_type,
        message: message || 'Unknown error',
        stack_trace: stack_trace || null,
        context: metadata || {},
        severity: severity || 'error',
      })
    }

    return new Response(JSON.stringify({ logged: true }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
`;

  return [
    { path: "migrations/logging.sql", content: sql, category: "sql" },
    { path: "functions/api-logger/index.ts", content: edgeFn, category: "functions" },
  ];
}

// ─── Module: Feature Flags ───────────────────────────────────────────────────

function generateFeatureFlagsModule(config: ProjectConfig): GeneratedFile[] {
  const adminRole = getAdminRoleName(config);
  const sql = `-- ============================================================
-- Module: Feature Flags
-- SECURITY: Only admins can create/update/delete flags.
-- All authenticated users can read flags.
-- ============================================================

CREATE TABLE public.feature_flags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT UNIQUE NOT NULL,
  description TEXT,
  enabled BOOLEAN NOT NULL DEFAULT false,
  metadata JSONB DEFAULT '{}',
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.feature_flags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can read flags"
  ON public.feature_flags FOR SELECT TO authenticated
  USING (true);

${adminRole ? `CREATE POLICY "Admins can insert flags"
  ON public.feature_flags FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), '${adminRole}'));

CREATE POLICY "Admins can update flags"
  ON public.feature_flags FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));

CREATE POLICY "Admins can delete flags"
  ON public.feature_flags FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));` : '-- No admin role defined, feature flags are service-role only for management'}

CREATE OR REPLACE FUNCTION public.is_feature_enabled(_flag_key TEXT)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    (SELECT enabled FROM public.feature_flags WHERE key = _flag_key),
    false
  )
$$;

CREATE TRIGGER update_feature_flags_updated_at
  BEFORE UPDATE ON public.feature_flags
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
`;

  return [{ path: "migrations/feature_flags.sql", content: sql, category: "sql" }];
}

// ─── Module: Background Jobs ─────────────────────────────────────────────────

function generateBackgroundJobsModule(config: ProjectConfig): GeneratedFile[] {
  const adminRole = getAdminRoleName(config);
  const sql = `-- ============================================================
-- Module: Background Jobs
-- SECURITY: Admins can manage all jobs.
-- Users can view their own jobs.
-- ============================================================

CREATE TYPE public.job_status AS ENUM ('pending', 'processing', 'failed', 'completed');

CREATE TABLE public.jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  payload JSONB DEFAULT '{}',
  status public.job_status NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  scheduled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  error TEXT,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_jobs_status_scheduled ON public.jobs(status, scheduled_at);
CREATE INDEX idx_jobs_created_by ON public.jobs(created_by);

CREATE POLICY "Users can view own jobs"
  ON public.jobs FOR SELECT TO authenticated
  USING (auth.uid() = created_by);

${adminRole ? `CREATE POLICY "Admins can manage all jobs"
  ON public.jobs FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), '${adminRole}'));` : ''}

CREATE POLICY "Service can manage jobs"
  ON public.jobs FOR ALL TO service_role
  USING (true);

CREATE OR REPLACE FUNCTION public.claim_job(_job_type TEXT DEFAULT NULL)
RETURNS SETOF public.jobs LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  claimed public.jobs;
BEGIN
  SELECT * INTO claimed
  FROM public.jobs
  WHERE status = 'pending'
    AND scheduled_at <= now()
    AND attempts < max_attempts
    AND (_job_type IS NULL OR type = _job_type)
  ORDER BY scheduled_at ASC
  LIMIT 1
  FOR UPDATE SKIP LOCKED;

  IF claimed.id IS NOT NULL THEN
    UPDATE public.jobs
    SET status = 'processing',
        started_at = now(),
        attempts = attempts + 1
    WHERE id = claimed.id;

    claimed.status := 'processing';
    claimed.started_at := now();
    claimed.attempts := claimed.attempts + 1;
    RETURN NEXT claimed;
  END IF;
  RETURN;
END;
$$;
`;

  const workerFn = `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  try {
    const body = await req.json().catch(() => ({}))
    const jobType = body.job_type || null

    const { data: jobs, error: claimError } = await supabase
      .rpc('claim_job', { _job_type: jobType })

    if (claimError) throw claimError
    if (!jobs || jobs.length === 0) {
      return new Response(JSON.stringify({ message: 'No jobs available' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const job = jobs[0]

    try {
      switch (job.type) {
        case 'send_email':
          break
        case 'generate_report':
          break
        default:
          console.log(\`Processing job type: \${job.type}\`, job.payload)
      }

      await supabase
        .from('jobs')
        .update({ status: 'completed', completed_at: new Date().toISOString() })
        .eq('id', job.id)

      return new Response(JSON.stringify({ processed: job.id, type: job.type }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    } catch (processingError) {
      const newStatus = job.attempts >= job.max_attempts ? 'failed' : 'pending'
      await supabase
        .from('jobs')
        .update({
          status: newStatus,
          error: processingError.message,
          started_at: null,
        })
        .eq('id', job.id)

      throw processingError
    }
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
`;

  return [
    { path: "migrations/background_jobs.sql", content: sql, category: "sql" },
    { path: "functions/job-worker/index.ts", content: workerFn, category: "functions" },
  ];
}

// ─── API Integration Framework ───────────────────────────────────────────────

function generateIntegrationFramework(): GeneratedFile[] {
  const baseClient = `/**
 * Base HTTP Client
 */

export interface ClientOptions {
  headers?: Record<string, string>;
  timeout?: number;
}

export class BaseClient {
  private baseUrl: string;
  private headers: Record<string, string>;
  private timeout: number;

  constructor(baseUrl: string, options: ClientOptions = {}) {
    this.baseUrl = baseUrl.replace(/\\/$/, '');
    this.headers = { 'Content-Type': 'application/json', ...options.headers };
    this.timeout = options.timeout ?? 30000;
  }

  async request<T = unknown>(method: string, path: string, body?: unknown): Promise<T> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeout);
    try {
      const response = await fetch(\`\${this.baseUrl}\${path}\`, {
        method, headers: this.headers,
        body: body ? JSON.stringify(body) : undefined,
        signal: controller.signal,
      });
      if (!response.ok) {
        const errorBody = await response.text();
        throw new Error(\`HTTP \${response.status}: \${errorBody}\`);
      }
      return await response.json() as T;
    } finally { clearTimeout(timer); }
  }

  get<T = unknown>(path: string) { return this.request<T>('GET', path); }
  post<T = unknown>(path: string, body: unknown) { return this.request<T>('POST', path, body); }
  put<T = unknown>(path: string, body: unknown) { return this.request<T>('PUT', path, body); }
  delete<T = unknown>(path: string) { return this.request<T>('DELETE', path); }
}
`;

  const retryWrapper = `/**
 * Retry Wrapper with exponential backoff
 */

export interface RetryOptions {
  maxRetries?: number;
  initialDelayMs?: number;
  maxDelayMs?: number;
  backoffFactor?: number;
  retryOn?: (error: Error) => boolean;
}

export async function withRetry<T>(
  fn: () => Promise<T>,
  options: RetryOptions = {}
): Promise<T> {
  const { maxRetries = 3, initialDelayMs = 1000, maxDelayMs = 30000, backoffFactor = 2, retryOn = () => true } = options;
  let lastError: Error;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try { return await fn(); } catch (error) {
      lastError = error instanceof Error ? error : new Error(String(error));
      if (attempt === maxRetries || !retryOn(lastError)) throw lastError;
      const delay = Math.min(initialDelayMs * Math.pow(backoffFactor, attempt), maxDelayMs);
      await new Promise((resolve) => setTimeout(resolve, delay * (0.5 + Math.random() * 0.5)));
    }
  }
  throw lastError!;
}
`;

  const webhookHandler = `/**
 * Webhook Handler — HMAC-SHA256 signature verification
 */

export async function verifyWebhookSignature(
  payload: string, signature: string, secret: string
): Promise<boolean> {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey('raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(payload));
  const computed = Array.from(new Uint8Array(sig)).map((b) => b.toString(16).padStart(2, '0')).join('');
  if (computed.length !== signature.length) return false;
  let result = 0;
  for (let i = 0; i < computed.length; i++) result |= computed.charCodeAt(i) ^ signature.charCodeAt(i);
  return result === 0;
}
`;

  const exampleIntegration = `import { BaseClient } from './base-client.ts';
import { withRetry } from './retry-wrapper.ts';

const apiClient = new BaseClient('https://api.example.com/v1', {
  headers: { 'Authorization': \`Bearer \${Deno.env.get('EXAMPLE_API_KEY') || ''}\` },
  timeout: 15000,
});

interface ExampleUser { id: string; name: string; email: string; }

export async function getUser(userId: string): Promise<ExampleUser> {
  return withRetry(() => apiClient.get<ExampleUser>(\`/users/\${userId}\`), { maxRetries: 2 });
}

export async function createUser(data: Omit<ExampleUser, 'id'>): Promise<ExampleUser> {
  return withRetry(() => apiClient.post<ExampleUser>('/users', data), {
    maxRetries: 1, retryOn: (error) => !error.message.includes('HTTP 4'),
  });
}
`;

  return [
    { path: "integrations/base-client.ts", content: baseClient, category: "functions" },
    { path: "integrations/retry-wrapper.ts", content: retryWrapper, category: "functions" },
    { path: "integrations/webhook-handler.ts", content: webhookHandler, category: "functions" },
    { path: "integrations/example-integration.ts", content: exampleIntegration, category: "functions" },
  ];
}

// ─── Seed Data ───────────────────────────────────────────────────────────────

function generateSeed(config: ProjectConfig): string {
  const lines: string[] = ["-- Seed Data", ""];

  // Admin bootstrap instructions
  if (config.roles.length > 0) {
    const adminRole = getAdminRoleName(config) || config.roles[0]?.name || 'admin';
    lines.push("-- ============================================================");
    lines.push("-- ADMIN BOOTSTRAP");
    lines.push("-- Run this with service_role or via SQL Editor to create the first admin.");
    lines.push("-- Replace <your-user-id> with the UUID from auth.users after signup.");
    lines.push("-- ============================================================");
    lines.push(`-- INSERT INTO public.user_roles (user_id, role) VALUES ('<your-user-id>', '${adminRole}');`);
    lines.push("");
    lines.push("-- ALTERNATIVE: The 'Bootstrap first admin' RLS policy allows the");
    lines.push("-- first user to self-assign admin via the frontend if no admin exists yet.");
    lines.push("");
  }

  for (const table of config.tables) {
    if (!table.name || table.columns.length === 0) continue;
    const cols = table.columns.filter((c) => !c.isPrimary && c.name !== "created_at" && c.name !== "updated_at" && c.name !== "deleted_at");
    if (cols.length === 0) continue;
    const colNames = cols.map((c) => c.name).join(", ");
    const sampleValues = cols.map((c) => {
      switch (c.type) {
        case "text": case "varchar": return `'sample_${c.name}'`;
        case "int": case "bigint": case "serial": case "bigserial": return "1";
        case "float": return "1.0";
        case "boolean": return "true";
        case "uuid": return "gen_random_uuid()";
        case "timestamp": case "timestamptz": case "date": return "now()";
        case "jsonb": case "json": return "'{}'";
        default: return "NULL";
      }
    }).join(", ");
    // Comment out because user_id / organization_id are required at runtime
    lines.push(`-- INSERT INTO public.${table.name} (${colNames}) VALUES (${sampleValues});`);
    lines.push(`-- NOTE: user_id${config.features.multiTenancy ? ' and organization_id are' : ' is'} required. Run inserts after signing up.`);
  }
  return lines.join("\n");
}

// ─── Edge Functions ──────────────────────────────────────────────────────────

function generateEdgeFunction(tableName: string, config: ProjectConfig): string {
  return `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  const url = new URL(req.url)
  const method = req.method

  try {
    if (method === 'GET') {
      const page = parseInt(url.searchParams.get('page') || '1')
      const limit = parseInt(url.searchParams.get('limit') || '20')
      const offset = (page - 1) * limit

      const { data, error, count } = await supabase
        .from('${tableName}')
        .select('*', { count: 'exact' })
        .range(offset, offset + limit - 1)

      if (error) throw error
      return new Response(JSON.stringify({ data, count, page, limit }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'POST') {
      const body = await req.json()
      const { data, error } = await supabase.from('${tableName}').insert(body).select().single()
      if (error) throw error
      return new Response(JSON.stringify(data), {
        status: 201,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'PUT' || method === 'PATCH') {
      const id = url.searchParams.get('id')
      if (!id) throw new Error('Missing id parameter')
      const body = await req.json()
      const { data, error } = await supabase.from('${tableName}').update(body).eq('id', id).select().single()
      if (error) throw error
      return new Response(JSON.stringify(data), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'DELETE') {
      const id = url.searchParams.get('id')
      if (!id) throw new Error('Missing id parameter')
      ${config.features.softDelete
        ? `const { error } = await supabase.from('${tableName}').update({ deleted_at: new Date().toISOString() }).eq('id', id)`
        : `const { error } = await supabase.from('${tableName}').delete().eq('id', id)`
      }
      if (error) throw error
      return new Response(JSON.stringify({ success: true }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    return new Response('Method not allowed', { status: 405, headers: corsHeaders })
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })
  }
})
`;
}

// ─── Frontend Files (complete runnable Vite + React project) ─────────────────

function generateFrontendFiles(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const hasMT = config.features.multiTenancy;
  const hasRoles = config.roles.length > 0;
  const adminRole = getAdminRoleName(config);

  // ── package.json ───────────────────────────────────────────────────────────
  files.push({
    path: "frontend/package.json",
    content: JSON.stringify({
      name: config.projectName || "generated-app",
      private: true,
      version: "0.0.1",
      type: "module",
      scripts: {
        dev: "vite",
        build: "tsc -b && vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1",
        "react-router-dom": "^6.30.0",
        "@supabase/supabase-js": "^2.49.0",
        "lucide-react": "^0.462.0",
      },
      devDependencies: {
        "@types/react": "^18.3.18",
        "@types/react-dom": "^18.3.5",
        "@vitejs/plugin-react": "^4.3.4",
        typescript: "~5.6.2",
        vite: "^6.0.5",
        tailwindcss: "^4.0.0",
        "@tailwindcss/vite": "^4.0.0",
      },
    }, null, 2),
    category: "frontend",
  });

  // ── index.html ─────────────────────────────────────────────────────────────
  files.push({
    path: "frontend/index.html",
    content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${config.projectName || "App"}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
    category: "frontend",
  });

  // ── src/main.tsx ───────────────────────────────────────────────────────────
  files.push({
    path: "frontend/src/main.tsx",
    content: `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);`,
    category: "frontend",
  });

  // ── src/index.css (Tailwind v4) ────────────────────────────────────────────
  files.push({
    path: "frontend/src/index.css",
    content: `@import "tailwindcss";`,
    category: "frontend",
  });

  // ── src/lib/supabase.ts ────────────────────────────────────────────────────
  files.push({
    path: "frontend/src/lib/supabase.ts",
    content: `import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    'Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY. ' +
    'Copy .env.example to .env and fill in your Supabase credentials.'
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);`,
    category: "frontend",
  });

  // ── vite.config.ts ─────────────────────────────────────────────────────────
  files.push({
    path: "frontend/vite.config.ts",
    content: `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import path from 'path';

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});`,
    category: "frontend",
  });

  // ── tsconfig.json ──────────────────────────────────────────────────────────
  files.push({
    path: "frontend/tsconfig.json",
    content: JSON.stringify({
      files: [],
      references: [{ path: "./tsconfig.app.json" }],
      compilerOptions: {
        baseUrl: ".",
        paths: { "@/*": ["./src/*"] },
      },
    }, null, 2),
    category: "frontend",
  });

  // ── tsconfig.app.json ─────────────────────────────────────────────────────
  files.push({
    path: "frontend/tsconfig.app.json",
    content: JSON.stringify({
      compilerOptions: {
        target: "ES2020",
        useDefineForClassFields: true,
        lib: ["ES2020", "DOM", "DOM.Iterable"],
        module: "ESNext",
        skipLibCheck: true,
        moduleResolution: "bundler",
        allowImportingTsExtensions: true,
        isolatedModules: true,
        moduleDetection: "force",
        noEmit: true,
        jsx: "react-jsx",
        strict: false,
        noUnusedLocals: false,
        noUnusedParameters: false,
        baseUrl: ".",
        paths: { "@/*": ["./src/*"] },
      },
      include: ["src"],
    }, null, 2),
    category: "frontend",
  });

  // ── .env.example ───────────────────────────────────────────────────────────
  files.push({
    path: "frontend/.env.example",
    content: `# Copy this file to .env and fill in your Supabase credentials.
VITE_SUPABASE_URL=https://your-project-id.supabase.co
VITE_SUPABASE_ANON_KEY=your-anon-key-here`,
    category: "frontend",
  });

  // ── useAuth hook ──────────────────────────────────────────────────────────
  files.push({
    path: "frontend/src/hooks/useAuth.ts",
    content: `import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import type { User, Session } from '@supabase/supabase-js';

export function useAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [session, setSession] = useState<Session | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
      setUser(session?.user ?? null);
      setLoading(false);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
      setUser(session?.user ?? null);
      setLoading(false);
    });

    return () => subscription.unsubscribe();
  }, []);

  const signOut = async () => {
    await supabase.auth.signOut();
    window.location.href = '/login';
  };

  return { user, session, loading, signOut };
}`,
    category: "frontend",
  });

  // ── RequireAuth component ─────────────────────────────────────────────────
  files.push({
    path: "frontend/src/components/RequireAuth.tsx",
    content: `import { useEffect } from 'react';
import { useAuth } from '../hooks/useAuth';

export default function RequireAuth({ children }: { children: React.ReactNode }) {
  const { user, loading } = useAuth();

  useEffect(() => {
    if (!loading && !user) {
      window.location.href = '/login';
    }
  }, [user, loading]);

  if (loading) return <div className="min-h-screen flex items-center justify-center"><p>Loading…</p></div>;
  if (!user) return null;
  return <>{children}</>;
}`,
    category: "frontend",
  });

  // ── Nav component ─────────────────────────────────────────────────────────
  const navLinks = config.tables.map(t => 
    `        <a href="/${t.name}" className={cn("px-3 py-1.5 rounded text-sm font-medium", path === "/${t.name}" ? "bg-blue-100 text-blue-800" : "text-gray-600 hover:text-gray-900 hover:bg-gray-100")}>${capitalize(t.name)}</a>`
  ).join("\n");

  files.push({
    path: "frontend/src/components/Nav.tsx",
    content: `import { useAuth } from '../hooks/useAuth';
${hasRoles ? "import { useUserRole } from '../hooks/useUserRole';" : ""}

function cn(...classes: (string | false | undefined)[]) { return classes.filter(Boolean).join(' '); }

export default function Nav() {
  const { user, signOut } = useAuth();
${hasRoles ? "  const { role } = useUserRole();" : ""}
  const path = window.location.pathname;

  if (!user) return null;

  return (
    <nav className="bg-white shadow-sm border-b px-4 h-14 flex items-center justify-between">
      <div className="flex items-center gap-1">
        <a href="/" className={cn("px-3 py-1.5 rounded text-sm font-medium", path === "/" ? "bg-blue-100 text-blue-800" : "text-gray-600 hover:text-gray-900 hover:bg-gray-100")}>Dashboard</a>
${navLinks}
      </div>
      <div className="flex items-center gap-3">
${hasRoles ? `        {role && <span className="text-xs font-semibold px-2 py-0.5 bg-blue-100 text-blue-800 rounded-full uppercase">{role}</span>}` : ""}
        <span className="text-sm text-gray-500">{user.email}</span>
        <button onClick={signOut} className="text-sm text-red-600 hover:underline">Sign Out</button>
      </div>
    </nav>
  );
}`,
    category: "frontend",
  });

  // ── useOrganization hook (multi-tenancy only) ──────────────────────────────
  if (hasMT) {
    files.push({
      path: "frontend/src/hooks/useOrganization.ts",
      content: `import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

let cachedOrgId: string | null = null;

export function useOrganization() {
  const [orgId, setOrgId] = useState<string | null>(cachedOrgId);
  const [loading, setLoading] = useState(!cachedOrgId);

  useEffect(() => {
    if (cachedOrgId) return;
    supabase.rpc('current_organization').then(({ data, error }) => {
      if (!error && data) {
        cachedOrgId = data;
        setOrgId(data);
      }
      setLoading(false);
    });
  }, []);

  return { orgId, loading };
}`,
      category: "frontend",
    });
  }

  // ── useUserRole hook (roles only) ──────────────────────────────────────────
  if (hasRoles) {
    files.push({
      path: "frontend/src/hooks/useUserRole.ts",
      content: `import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

let cachedRole: string | null = null;

export function useUserRole() {
  const [role, setRole] = useState<string | null>(cachedRole);
  const [loading, setLoading] = useState(!cachedRole);

  useEffect(() => {
    if (cachedRole) { setRole(cachedRole); setLoading(false); return; }
    supabase.rpc('get_my_role').then(({ data, error }) => {
      if (!error && data) {
        cachedRole = data as string;
        setRole(data as string);
      }
      setLoading(false);
    });
  }, []);

  const isAdmin = role === '${adminRole}';

  const bootstrapAdmin = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return false;
    const { error } = await supabase.from('user_roles').insert({ user_id: user.id, role: '${adminRole}' });
    if (!error) {
      cachedRole = '${adminRole}';
      setRole('${adminRole}');
      return true;
    }
    return false;
  };

  return { role, loading, isAdmin, bootstrapAdmin };
}`,
      category: "frontend",
    });
  }

  // ── App.tsx ────────────────────────────────────────────────────────────────
  files.push({
    path: "frontend/src/App.tsx",
    content: `import { BrowserRouter, Routes, Route } from 'react-router-dom';
import RequireAuth from './components/RequireAuth';
${config.frontendOptions.loginSignup ? "import Login from './pages/Login';\nimport Signup from './pages/Signup';" : ""}
${config.frontendOptions.roleDashboards ? "import Dashboard from './pages/Dashboard';" : ""}
${config.frontendOptions.crudPages ? config.tables.map((t) => `import ${capitalize(t.name)}List from './pages/${capitalize(t.name)}List';`).join("\n") : ""}

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
${config.frontendOptions.loginSignup ? '        <Route path="/login" element={<Login />} />\n        <Route path="/signup" element={<Signup />} />' : ""}
        <Route path="/" element={<RequireAuth>${config.frontendOptions.roleDashboards ? "<Dashboard />" : "<div className=\"p-8\"><h1 className=\"text-2xl font-bold\">Home</h1></div>"}</RequireAuth>} />
${config.frontendOptions.crudPages ? config.tables.map((t) => `        <Route path="/${t.name}" element={<RequireAuth><${capitalize(t.name)}List /></RequireAuth>} />`).join("\n") : ""}
      </Routes>
    </BrowserRouter>
  );
}`,
    category: "frontend",
  });

  // ── Login.tsx ──────────────────────────────────────────────────────────────
  if (config.frontendOptions.loginSignup) {
    files.push({
      path: "frontend/src/pages/Login.tsx",
      content: `import { useState } from 'react';
import { supabase } from '../lib/supabase';
import { Link } from 'react-router-dom';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) setError(error.message);
    else window.location.href = '/';
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <form onSubmit={handleLogin} className="w-full max-w-md space-y-4 p-8 bg-white rounded-lg shadow">
        <h1 className="text-2xl font-bold">Sign In</h1>
        {error && <p className="text-red-600 text-sm">{error}</p>}
        <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="w-full border p-2 rounded" required />
        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" className="w-full border p-2 rounded" required />
        <button type="submit" className="w-full bg-blue-600 text-white p-2 rounded hover:bg-blue-700">Sign In</button>
        <p className="text-sm text-center text-gray-600">Don't have an account? <Link to="/signup" className="text-blue-600 hover:underline">Sign Up</Link></p>
      </form>
    </div>
  );
}`,
      category: "frontend",
    });

    // ── Signup.tsx ──────────────────────────────────────────────────────────
    files.push({
      path: "frontend/src/pages/Signup.tsx",
      content: `import { useState } from 'react';
import { supabase } from '../lib/supabase';
import { Link } from 'react-router-dom';

export default function Signup() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');

  const handleSignup = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setMessage('');
    const { error } = await supabase.auth.signUp({ email, password });
    if (error) setError(error.message);
    else setMessage('Check your email for a confirmation link.');
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <form onSubmit={handleSignup} className="w-full max-w-md space-y-4 p-8 bg-white rounded-lg shadow">
        <h1 className="text-2xl font-bold">Sign Up</h1>
        {error && <p className="text-red-600 text-sm">{error}</p>}
        {message && <p className="text-green-600 text-sm">{message}</p>}
        <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="w-full border p-2 rounded" required />
        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password (min 6 chars)" className="w-full border p-2 rounded" minLength={6} required />
        <button type="submit" className="w-full bg-blue-600 text-white p-2 rounded hover:bg-blue-700">Create Account</button>
        <p className="text-sm text-center text-gray-600">Already have an account? <Link to="/login" className="text-blue-600 hover:underline">Sign In</Link></p>
      </form>
    </div>
  );
}`,
      category: "frontend",
    });
  }

  // ── Dashboard.tsx ──────────────────────────────────────────────────────────
  if (config.frontendOptions.roleDashboards) {
    const dashLinks = config.tables.map(t => `          <a href="/${t.name}" className="px-4 py-2 bg-white rounded shadow hover:shadow-md transition text-blue-600 font-medium">${capitalize(t.name)}</a>`).join("\n");
    files.push({
      path: "frontend/src/pages/Dashboard.tsx",
      content: `import { useState } from 'react';
import Nav from '../components/Nav';
${hasMT ? "import { useOrganization } from '../hooks/useOrganization';" : ""}
${hasRoles ? "import { useUserRole } from '../hooks/useUserRole';" : ""}

export default function Dashboard() {
${hasMT ? "  const { orgId, loading: orgLoading } = useOrganization();" : ""}
${hasRoles ? "  const { role, isAdmin, bootstrapAdmin, loading: roleLoading } = useUserRole();" : ""}
${hasRoles ? "  const [bootstrapping, setBootstrapping] = useState(false);" : ""}

${hasRoles ? `  const handleBootstrap = async () => {
    setBootstrapping(true);
    const success = await bootstrapAdmin();
    if (!success) alert('Could not assign admin role. An admin may already exist.');
    setBootstrapping(false);
  };` : ""}

  return (
    <div className="min-h-screen bg-gray-50">
      <Nav />
      <main className="p-8 max-w-4xl mx-auto">
${hasMT ? `        {orgLoading ? <p>Loading…</p> : <p className="text-sm text-gray-500 mb-4">Organization: <code className="bg-gray-100 px-1 rounded">{orgId ?? 'None'}</code></p>}` : ""}

${hasRoles ? `        {/* Admin Section */}
        {!roleLoading && isAdmin && (
          <div className="mb-8 p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <h2 className="text-lg font-semibold text-blue-900 mb-2">🛡️ Admin Panel</h2>
            <p className="text-sm text-blue-700 mb-2">You have admin privileges. You can manage all records across CRUD pages.</p>
          </div>
        )}

        {/* Bootstrap: show when no role and roles are configured */}
        {!roleLoading && !role && (
          <div className="mb-8 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
            <h2 className="text-lg font-semibold text-yellow-900 mb-2">⚡ No Role Assigned</h2>
            <p className="text-sm text-yellow-700 mb-3">If you are the first user, you can bootstrap yourself as admin.</p>
            <button
              onClick={handleBootstrap}
              disabled={bootstrapping}
              className="px-4 py-2 bg-yellow-600 text-white rounded hover:bg-yellow-700 disabled:opacity-50 text-sm font-medium"
            >
              {bootstrapping ? 'Assigning…' : 'Become Admin'}
            </button>
          </div>
        )}` : ""}

        <h2 className="text-lg font-semibold mb-4">Quick Links</h2>
        <div className="flex flex-wrap gap-4">
${dashLinks}
        </div>
      </main>
    </div>
  );
}`,
      category: "frontend",
    });
  }

  // ── CRUD List pages with Create/Edit forms ─────────────────────────────────
  if (config.frontendOptions.crudPages) {
    for (const table of config.tables) {
      if (!table.name) continue;
      const cols = table.columns.filter(c => !["id", "created_at", "updated_at", "deleted_at", "user_id", "organization_id"].includes(c.name));
      const orgFilter = hasMT ? `\n    if (orgId) query = query.eq('organization_id', orgId);` : "";
      const orgInsert = hasMT ? `, organization_id: orgId` : "";

      // Generate form fields based on column types
      const formFieldsJsx = cols.map(c => {
        const inputType = c.type === 'boolean' ? 'checkbox' :
          c.type === 'int' || c.type === 'bigint' || c.type === 'float' || c.type === 'serial' || c.type === 'bigserial' ? 'number' :
          c.type === 'date' ? 'date' :
          c.type === 'timestamp' || c.type === 'timestamptz' ? 'datetime-local' :
          'text';
        
        if (c.type === 'boolean') {
          return `            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" checked={!!form.${c.name}} onChange={(e) => setForm({...form, ${c.name}: e.target.checked})} className="rounded" />
              ${c.name}
            </label>`;
        }
        if (c.type === 'jsonb' || c.type === 'json') {
          return `            <textarea placeholder="${c.name}" value={typeof form.${c.name} === 'object' ? JSON.stringify(form.${c.name}) : (form.${c.name} || '')} onChange={(e) => { try { setForm({...form, ${c.name}: JSON.parse(e.target.value)}); } catch { setForm({...form, ${c.name}: e.target.value}); } }} className="w-full border p-2 rounded text-sm" rows={2} />`;
        }
        return `            <input type="${inputType}" placeholder="${c.name}" value={form.${c.name} ?? ''} onChange={(e) => setForm({...form, ${c.name}: ${inputType === 'number' ? 'Number(e.target.value)' : 'e.target.value'}})} className="w-full border p-2 rounded text-sm" ${c.isRequired ? 'required' : ''} />`;
      }).join("\n");

      const emptyForm = `{${cols.map(c => {
        if (c.type === 'boolean') return ` ${c.name}: false`;
        if (c.type === 'int' || c.type === 'bigint' || c.type === 'float') return ` ${c.name}: 0`;
        if (c.type === 'jsonb' || c.type === 'json') return ` ${c.name}: {}`;
        return ` ${c.name}: ''`;
      }).join(',')}}`;

      files.push({
        path: `frontend/src/pages/${capitalize(table.name)}List.tsx`,
        content: `import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
${hasMT ? "import { useOrganization } from '../hooks/useOrganization';" : ""}
${hasRoles ? "import { useUserRole } from '../hooks/useUserRole';" : ""}

export default function ${capitalize(table.name)}List() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<any>(${emptyForm});
  const [error, setError] = useState('');
${hasMT ? "  const { orgId } = useOrganization();" : ""}
${hasRoles ? "  const { isAdmin } = useUserRole();" : ""}

  const fetchItems = async () => {
    setLoading(true);
    let query = supabase.from('${table.name}').select('*');${orgFilter}
    const { data } = await query.order('created_at', { ascending: false });
    setItems(data || []);
    setLoading(false);
  };

  useEffect(() => { fetchItems(); }, [${hasMT ? "orgId" : ""}]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    
    if (editingId) {
      const { error } = await supabase.from('${table.name}').update(form).eq('id', editingId);
      if (error) { setError(error.message); return; }
    } else {
      const { data: { user } } = await supabase.auth.getUser();
      const { error } = await supabase.from('${table.name}').insert({ ...form, user_id: user?.id${orgInsert} });
      if (error) { setError(error.message); return; }
    }
    
    setForm(${emptyForm});
    setEditingId(null);
    setShowForm(false);
    fetchItems();
  };

  const handleEdit = (item: any) => {
    setForm({${cols.map(c => ` ${c.name}: item.${c.name}`).join(',')} });
    setEditingId(item.id);
    setShowForm(true);
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure?')) return;
    await supabase.from('${table.name}').delete().eq('id', id);
    fetchItems();
  };

  const handleCancel = () => {
    setForm(${emptyForm});
    setEditingId(null);
    setShowForm(false);
    setError('');
  };

  if (loading) return <div className="p-8">Loading…</div>;

  return (
    <div className="p-8 max-w-6xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">${capitalize(table.name)}</h1>
        <div className="flex gap-2">
          {!showForm && (
            <button onClick={() => setShowForm(true)} className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 text-sm font-medium">
              + New ${capitalize(table.name)}
            </button>
          )}
          <a href="/" className="px-4 py-2 text-sm text-gray-600 hover:text-gray-900">← Back</a>
        </div>
      </div>

      {/* Create / Edit Form */}
      {showForm && (
        <form onSubmit={handleSubmit} className="mb-6 p-4 bg-white rounded-lg shadow border space-y-3">
          <h2 className="font-semibold text-lg">{editingId ? 'Edit' : 'New'} ${capitalize(table.name)}</h2>
          {error && <p className="text-red-600 text-sm">{error}</p>}
${formFieldsJsx}
          <div className="flex gap-2 pt-2">
            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 text-sm font-medium">
              {editingId ? 'Update' : 'Create'}
            </button>
            <button type="button" onClick={handleCancel} className="px-4 py-2 bg-gray-200 text-gray-700 rounded hover:bg-gray-300 text-sm">
              Cancel
            </button>
          </div>
        </form>
      )}

      <div className="overflow-x-auto">
        <table className="w-full border-collapse bg-white shadow rounded">
          <thead>
            <tr className="bg-gray-100">
${cols.map(c => `              <th className="text-left p-3 text-sm font-medium text-gray-600">${c.name}</th>`).join("\n")}
              <th className="text-right p-3 text-sm font-medium text-gray-600">Actions</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id} className="border-t hover:bg-gray-50">
${cols.map(c => `                <td className="p-3 text-sm">{String(item.${c.name} ?? '')}</td>`).join("\n")}
                <td className="p-3 text-sm text-right space-x-2">
                  <button onClick={() => handleEdit(item)} className="text-blue-600 hover:underline text-xs">Edit</button>
                  <button onClick={() => handleDelete(item.id)} className="text-red-600 hover:underline text-xs">Delete</button>
                </td>
              </tr>
            ))}
            {items.length === 0 && (
              <tr><td colSpan={${cols.length + 1}} className="p-8 text-center text-gray-400">No records found</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}`,
        category: "frontend",
      });
    }
  }

  return files;
}

// ─── Documentation ───────────────────────────────────────────────────────────

function generateReadme(config: ProjectConfig): string {
  const allFeatures: { key: keyof typeof config.features; label: string }[] = [
    { key: "auth", label: "Authentication (email/password)" },
    { key: "timestamps", label: "Auto timestamps" },
    { key: "softDelete", label: "Soft delete" },
    { key: "auditLogs", label: "Audit logging" },
    { key: "notifications", label: "Notification triggers" },
    { key: "fileUploads", label: "File uploads" },
    { key: "searchPagination", label: "Search & pagination" },
    { key: "rateLimiting", label: "Rate limiting" },
    { key: "multiTenancy", label: "Multi-tenancy (organizations)" },
    { key: "apiIntegrations", label: "API integration framework" },
    { key: "logging", label: "Centralized logging & analytics" },
    { key: "featureFlags", label: "Feature flags" },
    { key: "backgroundJobs", label: "Background job queue" },
  ];

  const enabledFeatures = allFeatures.filter((f) => config.features[f.key]);

  let readme = `# ${config.projectName}

${config.description || "Generated by Supabase Project Factory"}

## Architecture Overview

This project uses a modular architecture. Each feature is an independent module that generates its own migrations, RLS policies, and helper functions.

### Enabled Modules

${enabledFeatures.map((f) => `- ✅ ${f.label}`).join("\n")}

## Setup

1. Install Supabase CLI: \`npm install -g supabase\`
2. Initialize project: \`supabase init\`
3. Copy migration files to \`supabase/migrations/\`
4. Apply migrations: \`supabase db push\`
5. Deploy edge functions: \`supabase functions deploy\`
6. Copy \`.env.example\` to \`.env\` and fill in values
7. Start locally: \`supabase start\`

## Frontend Setup

1. \`cd frontend\`
2. \`cp .env.example .env\` and fill in Supabase credentials
3. \`npm install\`
4. \`npm run dev\`

## Structure

- \`migrations/\` — Versioned SQL migrations (schema, roles, RLS, modules)
- \`functions/\` — Edge function stubs for API endpoints
${config.features.apiIntegrations ? "- `integrations/` — HTTP client, retry logic, webhook templates\n" : ""}\
- \`frontend/\` — React + Tailwind frontend (Vite + TypeScript)
- \`seed.sql\` — Sample data for testing

## Tables

${config.tables.map((t) => `- \`${t.name}\` (${t.columns.length} columns)`).join("\n")}

## Roles

${config.roles.map((r) => `- \`${r.name}\``).join("\n") || "No roles defined"}
`;

  if (config.roles.length > 0) {
    readme += `
## Admin Bootstrap

The first user can self-assign admin via the Dashboard "Become Admin" button.
Alternatively, run this SQL with service_role:
\`\`\`sql
INSERT INTO public.user_roles (user_id, role) VALUES ('<your-user-id>', '${getAdminRoleName(config) || 'admin'}');
\`\`\`
`;
  }

  if (config.features.multiTenancy) {
    readme += `
## Multi-Tenancy

Tenant isolation is enforced via RLS policies. Every user table includes an \`organization_id\` column.
A "Home Organization" is auto-created for each new user on signup.

Key functions:
- \`is_tenant_member(org_id)\`: Check if user belongs to an org
- \`current_organization()\`: Get the user's current org ID
`;
  }

  readme += `
## Security Notes

- All tables have RLS enabled by default (deny-all without explicit policies)
- Owner-based baseline policies ensure users can always manage their own records
- Roles are stored in a separate \`user_roles\` table (not on profiles) to prevent escalation
- The \`has_role()\` function uses SECURITY DEFINER to avoid recursive RLS
`;

  return readme;
}

function generateApiDocs(config: ProjectConfig): string {
  const lines: string[] = [`# API Documentation — ${config.projectName}`, ""];

  for (const ep of config.apiEndpoints) {
    if (!ep.crud) continue;
    lines.push(`## ${ep.table}`, "");
    lines.push(`### GET /functions/v1/${ep.table}`);
    lines.push(`List all ${ep.table}. Supports \`?page=1&limit=20\`.`, "");
    lines.push(`### POST /functions/v1/${ep.table}`);
    lines.push(`Create a new ${ep.table} record.`, "");
    lines.push(`### PUT /functions/v1/${ep.table}?id=<uuid>`);
    lines.push(`Update a ${ep.table} record.`, "");
    lines.push(`### DELETE /functions/v1/${ep.table}?id=<uuid>`);
    lines.push(`Delete a ${ep.table} record.`, "");
  }

  if (config.features.rateLimiting) {
    lines.push("## Rate Limiter", "");
    lines.push("### POST /functions/v1/rate-limiter");
    lines.push("Check rate limit. Body: `{ endpoint, user_id?, ip_address? }`", "");
  }

  if (config.features.backgroundJobs) {
    lines.push("## Job Worker", "");
    lines.push("### POST /functions/v1/job-worker");
    lines.push("Claims and processes the next pending job. Body: `{ job_type? }`", "");
  }

  if (config.features.logging) {
    lines.push("## API Logger", "");
    lines.push("### POST /functions/v1/api-logger");
    lines.push("Log API metrics/activity/errors. Body: `{ endpoint?, status_code?, action?, error_type? }`", "");
  }

  return lines.join("\n");
}

function generateArchitectureDocs(config: ProjectConfig): string {
  const modules: string[] = [];

  if (config.features.auth) modules.push("- **Authentication**: Email/password auth via Supabase Auth");
  if (config.features.timestamps) modules.push("- **Timestamps**: Auto `created_at`/`updated_at` via trigger");
  if (config.features.softDelete) modules.push("- **Soft Delete**: `deleted_at` column + `_active` views");
  if (config.features.auditLogs) modules.push("- **Audit Logs**: Trigger-based change tracking on all tables");
  if (config.features.fileUploads) modules.push("- **File Uploads**: Storage bucket with user-scoped RLS");
  if (config.features.rateLimiting) modules.push("- **Rate Limiting**: Per-endpoint limits with IP/user tracking + edge function middleware");
  if (config.features.multiTenancy) modules.push("- **Multi-Tenancy**: Organization-based isolation with `is_tenant_member()` helper");
  if (config.features.apiIntegrations) modules.push("- **API Integrations**: Base HTTP client, retry wrapper, webhook verification");
  if (config.features.logging) modules.push("- **Centralized Logging**: Activity logs, error logs, API metrics + logger edge function");
  if (config.features.featureFlags) modules.push("- **Feature Flags**: Admin-managed flags with `is_feature_enabled()` helper");
  if (config.features.backgroundJobs) modules.push("- **Background Jobs**: Queue with `claim_job()` (SKIP LOCKED) + worker edge function");

  return `# Architecture — ${config.projectName}

## Module System

Each module is independent and generates its own:
- SQL migration file (numbered for ordering)
- RLS policies (secure by default)
- Helper functions (SECURITY DEFINER where needed)
- Edge functions (where applicable)

## Enabled Modules

${modules.join("\n")}

## Migration Order

\`\`\`
migrations/001_core.sql          — Tables, indexes, constraints${config.features.multiTenancy ? ' (+ organizations)' : ''}
migrations/002_roles.sql         — Role enum, user_roles table, has_role(), bootstrap policy
migrations/003_rls.sql           — Per-role RLS policies + owner-based baseline policies
migrations/004_*.sql             — Optional module migrations
seed.sql                         — Sample data + admin bootstrap instructions
\`\`\`

## Security Model

1. **Deny by default**: All tables have RLS enabled. No access without explicit policies.
2. **Owner-based baseline**: Users can always CRUD their own records (via \`user_id\`).
3. **Role separation**: Roles stored in \`user_roles\` table (not on profiles).
4. **Bootstrap policy**: First user can self-assign admin when no admins exist.
5. **No recursion**: \`has_role()\` uses SECURITY DEFINER to prevent RLS recursion.
6. **Tenant isolation**: Multi-tenancy uses \`is_tenant_member()\` for org-scoped access.
`;
}

function generateEnvExample(config: ProjectConfig): string {
  let env = `# ============================================================
# Environment Variables
# Copy this file to .env and fill in the values.
# ============================================================

# Supabase (required)
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
`;

  if (config.features.apiIntegrations) {
    env += `
# API Integrations
EXAMPLE_API_KEY=your-api-key
WEBHOOK_SECRET=your-webhook-secret
`;
  }

  return env;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
