import { ProjectConfig } from "@/types/project";

export interface GeneratedFile {
  path: string;
  content: string;
  category: "sql" | "functions" | "frontend" | "docs";
}

// ─── Orchestrator ────────────────────────────────────────────────────────────

export function generateProject(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // 1. Core schema
  files.push({ path: "migrations/001_core.sql", content: generateCoreSchema(config), category: "sql" });

  // 2. Roles setup (if roles defined)
  if (config.roles.length > 0) {
    files.push({ path: "migrations/002_roles.sql", content: generateRolesSetup(config), category: "sql" });
    files.push({ path: "migrations/003_rls.sql", content: generateRLS(config), category: "sql" });
  }

  // 3. Optional modules — each gets its own numbered migration
  let migrationIdx = 4;
  const optionalModules: { flag: keyof typeof config.features; fn: (c: ProjectConfig) => GeneratedFile[] }[] = [
    { flag: "auditLogs", fn: generateAuditLogModule },
    { flag: "softDelete", fn: generateSoftDeleteModule },
    { flag: "fileUploads", fn: generateStorageModule },
    { flag: "rateLimiting", fn: generateRateLimitingModule },
    { flag: "multiTenancy", fn: generateMultiTenancyModule },
    { flag: "logging", fn: generateLoggingModule },
    { flag: "featureFlags", fn: generateFeatureFlagsModule },
    { flag: "backgroundJobs", fn: generateBackgroundJobsModule },
  ];

  for (const mod of optionalModules) {
    if (config.features[mod.flag]) {
      const moduleFiles = mod.fn(config);
      // Prefix SQL files with migration index
      for (const f of moduleFiles) {
        if (f.category === "sql" && f.path.startsWith("migrations/")) {
          f.path = `migrations/${String(migrationIdx).padStart(3, "0")}_${f.path.replace("migrations/", "")}`;
          migrationIdx++;
        }
        files.push(f);
      }
    }
  }

  // 4. Seed data
  files.push({ path: "seed.sql", content: generateSeed(config), category: "sql" });

  // 5. Edge functions
  config.apiEndpoints.filter((e) => e.crud).forEach((ep) => {
    files.push({
      path: `functions/${ep.table}/index.ts`,
      content: generateEdgeFunction(ep.table, config),
      category: "functions",
    });
  });

  // 6. API Integration Framework
  if (config.features.apiIntegrations) {
    files.push(...generateIntegrationFramework());
  }

  // 7. Frontend (optional, unchanged)
  if (config.frontendOptions.enabled) {
    files.push(...generateFrontendFiles(config));
  }

  // 8. Documentation
  files.push({ path: "README.md", content: generateReadme(config), category: "docs" });
  files.push({ path: "API.md", content: generateApiDocs(config), category: "docs" });
  files.push({ path: "ARCHITECTURE.md", content: generateArchitectureDocs(config), category: "docs" });
  files.push({ path: ".env.example", content: generateEnvExample(config), category: "docs" });

  return files;
}

// ─── Core Schema ─────────────────────────────────────────────────────────────

function generateCoreSchema(config: ProjectConfig): string {
  const lines: string[] = [
    "-- ============================================================",
    "-- Generated by Supabase Project Factory",
    `-- Project: ${config.projectName}`,
    "-- ",
    "-- SECURITY: All tables have RLS enabled by default.",
    "-- Without explicit policies, no access is granted (deny-all).",
    "-- ============================================================",
    "",
  ];

  for (const table of config.tables) {
    if (!table.name) continue;

    lines.push(`-- ── Table: ${table.name} ──────────────────────────────────`);
    lines.push(`CREATE TABLE public.${table.name} (`);
    const colDefs: string[] = [];

    for (const col of table.columns) {
      if (!col.name) continue;
      let def = `  ${col.name} ${col.type.toUpperCase()}`;
      if (col.isPrimary) def += " PRIMARY KEY";
      if (col.type === "uuid" && col.isPrimary) def += " DEFAULT gen_random_uuid()";
      if (col.isRequired && !col.isPrimary) def += " NOT NULL";
      if (col.isUnique && !col.isPrimary) def += " UNIQUE";
      if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
      colDefs.push(def);
    }

    if (config.features.auth && !table.columns.some((c) => c.name === "user_id")) {
      colDefs.push("  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL");
    }

    if (config.features.timestamps) {
      if (!table.columns.some((c) => c.name === "created_at"))
        colDefs.push("  created_at TIMESTAMPTZ NOT NULL DEFAULT now()");
      if (!table.columns.some((c) => c.name === "updated_at"))
        colDefs.push("  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()");
    }

    if (config.features.softDelete) {
      colDefs.push("  deleted_at TIMESTAMPTZ");
    }

    if (config.features.multiTenancy) {
      colDefs.push("  organization_id UUID -- tenant isolation column");
    }

    lines.push(colDefs.join(",\n"));
    lines.push(");");
    lines.push("");

    // Indexes
    for (const col of table.columns) {
      if (col.isIndexed && !col.isPrimary) {
        lines.push(`CREATE INDEX idx_${table.name}_${col.name} ON public.${table.name}(${col.name});`);
      }
    }

    // RLS — secure by default
    lines.push(`-- SECURITY: RLS enabled. Without policies, all access is denied.`);
    lines.push(`ALTER TABLE public.${table.name} ENABLE ROW LEVEL SECURITY;`);
    lines.push("");
  }

  // Foreign keys for 1:1 and 1:N relationships
  for (const rel of config.relationships) {
    if (rel.type === "1:1" || rel.type === "1:N") {
      lines.push(
        `ALTER TABLE public.${rel.to.table} ADD COLUMN ${rel.from.table}_id UUID REFERENCES public.${rel.from.table}(id) ON DELETE CASCADE;`
      );
    } else if (rel.type === "N:N") {
      const jt = `${rel.from.table}_${rel.to.table}`;
      lines.push(`-- Junction table for N:N relationship`);
      lines.push(`CREATE TABLE public.${jt} (`);
      lines.push(`  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),`);
      lines.push(`  ${rel.from.table}_id UUID REFERENCES public.${rel.from.table}(id) ON DELETE CASCADE NOT NULL,`);
      lines.push(`  ${rel.to.table}_id UUID REFERENCES public.${rel.to.table}(id) ON DELETE CASCADE NOT NULL,`);
      lines.push(`  UNIQUE(${rel.from.table}_id, ${rel.to.table}_id)`);
      lines.push(`);`);
      lines.push(`ALTER TABLE public.${jt} ENABLE ROW LEVEL SECURITY;`);
      lines.push("");
    }
  }

  // Timestamp trigger
  if (config.features.timestamps) {
    lines.push(`
-- Auto-update updated_at on row changes
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
`);
    for (const table of config.tables) {
      if (!table.name) continue;
      lines.push(
        `CREATE TRIGGER update_${table.name}_updated_at BEFORE UPDATE ON public.${table.name} FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();`
      );
    }
  }

  return lines.join("\n");
}

// ─── Roles Setup ─────────────────────────────────────────────────────────────

function generateRolesSetup(config: ProjectConfig): string {
  const roleNames = config.roles.map((r) => `'${r.name}'`).join(", ");
  return `-- ============================================================
-- Role-Based Access Control Setup
-- SECURITY: Roles are stored in a separate table (not on profiles)
-- to prevent privilege escalation attacks.
-- ============================================================

CREATE TYPE public.app_role AS ENUM (${roleNames});

CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  UNIQUE (user_id, role)
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Security definer function to check roles (avoids RLS recursion)
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

-- Users can read their own roles
CREATE POLICY "Users can view own roles"
  ON public.user_roles FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Only admins can manage roles
CREATE POLICY "Admins can manage roles"
  ON public.user_roles FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));
`;
}

// ─── RLS Policies ────────────────────────────────────────────────────────────

function generateRLS(config: ProjectConfig): string {
  const lines: string[] = [
    "-- ============================================================",
    "-- Row Level Security Policies",
    "-- SECURITY: Each policy uses the has_role() security definer",
    "-- function to avoid recursive RLS evaluation.",
    "-- ============================================================",
    "",
  ];

  for (const role of config.roles) {
    if (!role.name) continue;
    for (const table of config.tables) {
      if (!table.name) continue;
      const perms = role.permissions[table.name];
      if (!perms) continue;

      const ownerClause = config.features.auth ? " OR auth.uid() = user_id" : "";
      const tenantClause = config.features.multiTenancy
        ? " OR public.is_tenant_member(organization_id)"
        : "";

      if (perms.select) {
        lines.push(`CREATE POLICY "${role.name}_select_${table.name}"`);
        lines.push(`  ON public.${table.name} FOR SELECT TO authenticated`);
        lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${ownerClause}${tenantClause});`);
        lines.push("");
      }
      if (perms.insert) {
        lines.push(`CREATE POLICY "${role.name}_insert_${table.name}"`);
        lines.push(`  ON public.${table.name} FOR INSERT TO authenticated`);
        lines.push(`  WITH CHECK (public.has_role(auth.uid(), '${role.name}')${ownerClause}${tenantClause});`);
        lines.push("");
      }
      if (perms.update) {
        lines.push(`CREATE POLICY "${role.name}_update_${table.name}"`);
        lines.push(`  ON public.${table.name} FOR UPDATE TO authenticated`);
        lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${ownerClause}${tenantClause});`);
        lines.push("");
      }
      if (perms.delete) {
        lines.push(`CREATE POLICY "${role.name}_delete_${table.name}"`);
        lines.push(`  ON public.${table.name} FOR DELETE TO authenticated`);
        lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${ownerClause}${tenantClause});`);
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

// ─── Module: Audit Logs ──────────────────────────────────────────────────────

function generateAuditLogModule(config: ProjectConfig): GeneratedFile[] {
  let sql = `-- ============================================================
-- Module: Audit Logging
-- Tracks all INSERT/UPDATE/DELETE operations on user tables.
-- SECURITY: Only admins can read audit logs.
-- ============================================================

CREATE TABLE public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name TEXT NOT NULL,
  record_id TEXT,
  action TEXT NOT NULL,
  old_data JSONB,
  new_data JSONB,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_audit_logs_created_at ON public.audit_logs(created_at);
CREATE INDEX idx_audit_logs_table_name ON public.audit_logs(table_name);

CREATE POLICY "Admins can view audit logs"
  ON public.audit_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.audit_trigger_fn()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, old_data, user_id)
    VALUES (TG_TABLE_NAME, OLD.id::TEXT, 'DELETE', to_jsonb(OLD), auth.uid());
    RETURN OLD;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, old_data, new_data, user_id)
    VALUES (TG_TABLE_NAME, NEW.id::TEXT, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), auth.uid());
    RETURN NEW;
  ELSIF TG_OP = 'INSERT' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, new_data, user_id)
    VALUES (TG_TABLE_NAME, NEW.id::TEXT, 'INSERT', to_jsonb(NEW), auth.uid());
    RETURN NEW;
  END IF;
END;
$$;
`;

  for (const table of config.tables) {
    if (!table.name) continue;
    sql += `\nCREATE TRIGGER audit_${table.name} AFTER INSERT OR UPDATE OR DELETE ON public.${table.name} FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_fn();`;
  }

  return [{ path: "migrations/audit.sql", content: sql, category: "sql" }];
}

// ─── Module: Soft Delete ─────────────────────────────────────────────────────

function generateSoftDeleteModule(config: ProjectConfig): GeneratedFile[] {
  const lines: string[] = [
    "-- ============================================================",
    "-- Module: Soft Delete",
    "-- Creates filtered views showing only non-deleted records.",
    "-- ============================================================",
    "",
  ];
  for (const table of config.tables) {
    if (!table.name) continue;
    lines.push(`CREATE VIEW public.${table.name}_active AS SELECT * FROM public.${table.name} WHERE deleted_at IS NULL;`);
  }
  return [{ path: "migrations/soft_delete.sql", content: lines.join("\n"), category: "sql" }];
}

// ─── Module: Storage ─────────────────────────────────────────────────────────

function generateStorageModule(_config: ProjectConfig): GeneratedFile[] {
  return [{
    path: "migrations/storage.sql",
    content: `-- ============================================================
-- Module: File Storage
-- SECURITY: Users can only access files in their own folder.
-- ============================================================

INSERT INTO storage.buckets (id, name, public) VALUES ('uploads', 'uploads', false);

CREATE POLICY "Users can upload files"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);

CREATE POLICY "Users can view own files"
  ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete own files"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);
`,
    category: "sql",
  }];
}

// ─── Module: Rate Limiting ───────────────────────────────────────────────────

function generateRateLimitingModule(_config: ProjectConfig): GeneratedFile[] {
  const sql = `-- ============================================================
-- Module: Rate Limiting
-- SECURITY: Admin-only management of rate limit rules.
-- Users can only view their own request logs.
-- ============================================================

CREATE TABLE public.api_rate_limits (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  endpoint TEXT NOT NULL,
  max_requests INT NOT NULL DEFAULT 100,
  window_seconds INT NOT NULL DEFAULT 60,
  role TEXT DEFAULT 'authenticated',
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;

-- SECURITY: Only admins can configure rate limits
CREATE POLICY "Admins can manage rate limits"
  ON public.api_rate_limits FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Authenticated can read rate limits"
  ON public.api_rate_limits FOR SELECT TO authenticated
  USING (true);

CREATE TABLE public.request_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  endpoint TEXT NOT NULL,
  ip_address INET,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.request_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_request_logs_endpoint_created ON public.request_logs(endpoint, created_at);
CREATE INDEX idx_request_logs_ip_created ON public.request_logs(ip_address, created_at);
CREATE INDEX idx_request_logs_user_created ON public.request_logs(user_id, created_at);

-- SECURITY: Users can only see their own request logs
CREATE POLICY "Users can view own request logs"
  ON public.request_logs FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all request logs"
  ON public.request_logs FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- Service role inserts request logs (from edge function)
CREATE POLICY "Service can insert request logs"
  ON public.request_logs FOR INSERT TO service_role
  WITH CHECK (true);

-- Cleanup function for old request logs
CREATE OR REPLACE FUNCTION public.cleanup_request_logs(retention_hours INT DEFAULT 24)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  DELETE FROM public.request_logs
  WHERE created_at < now() - (retention_hours || ' hours')::INTERVAL;
END;
$$;
`;

  const edgeFn = `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

/**
 * Rate Limiter Middleware
 * 
 * Usage: Call this function before processing a request to check
 * if the user/IP has exceeded their rate limit.
 * 
 * Returns 429 Too Many Requests with Retry-After header when exceeded.
 */
serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  try {
    const { endpoint, user_id, ip_address } = await req.json()

    // 1. Get rate limit config for this endpoint
    const { data: limitConfig } = await supabase
      .from('api_rate_limits')
      .select('*')
      .eq('endpoint', endpoint)
      .single()

    const maxRequests = limitConfig?.max_requests ?? 100
    const windowSeconds = limitConfig?.window_seconds ?? 60

    // 2. Count recent requests in the window
    const windowStart = new Date(Date.now() - windowSeconds * 1000).toISOString()

    let query = supabase
      .from('request_logs')
      .select('id', { count: 'exact' })
      .eq('endpoint', endpoint)
      .gte('created_at', windowStart)

    // Check by user_id first, then fall back to IP
    if (user_id) {
      query = query.eq('user_id', user_id)
    } else if (ip_address) {
      query = query.eq('ip_address', ip_address)
    }

    const { count } = await query

    // 3. Log this request
    await supabase.from('request_logs').insert({
      endpoint,
      user_id: user_id || null,
      ip_address: ip_address || null,
    })

    // 4. Check limit
    if ((count ?? 0) >= maxRequests) {
      return new Response(
        JSON.stringify({ error: 'Rate limit exceeded', retry_after: windowSeconds }),
        {
          status: 429,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json',
            'Retry-After': String(windowSeconds),
          },
        }
      )
    }

    return new Response(
      JSON.stringify({ allowed: true, remaining: maxRequests - (count ?? 0) - 1 }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
`;

  return [
    { path: "migrations/rate_limiting.sql", content: sql, category: "sql" },
    { path: "functions/rate-limiter/index.ts", content: edgeFn, category: "functions" },
  ];
}

// ─── Module: Multi-Tenancy ───────────────────────────────────────────────────

function generateMultiTenancyModule(config: ProjectConfig): GeneratedFile[] {
  let sql = `-- ============================================================
-- Module: Multi-Tenancy
-- SECURITY: Tenant isolation enforced via RLS.
-- organization_id column added to all user tables in core schema.
-- ============================================================

CREATE TABLE public.organizations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  owner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  settings JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.organization_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  organization_id UUID REFERENCES public.organizations(id) ON DELETE CASCADE NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, organization_id)
);

ALTER TABLE public.organization_members ENABLE ROW LEVEL SECURITY;

-- Helper: Check if the current user is a member of the given org
CREATE OR REPLACE FUNCTION public.is_tenant_member(_org_id UUID)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.organization_members
    WHERE user_id = auth.uid() AND organization_id = _org_id
  )
$$;

-- Helper: Get the user's current organization (first org they belong to)
CREATE OR REPLACE FUNCTION public.current_organization()
RETURNS UUID LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT organization_id FROM public.organization_members
  WHERE user_id = auth.uid()
  LIMIT 1
$$;

-- RLS: Members can see their own organizations
CREATE POLICY "Members can view own orgs"
  ON public.organizations FOR SELECT TO authenticated
  USING (public.is_tenant_member(id));

-- RLS: Owners can manage their orgs
CREATE POLICY "Owners can manage orgs"
  ON public.organizations FOR ALL TO authenticated
  USING (owner_id = auth.uid());

-- RLS: Members can see their own memberships
CREATE POLICY "Members can view own memberships"
  ON public.organization_members FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- RLS: Org admins can manage members
CREATE POLICY "Org admins can manage members"
  ON public.organization_members FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.organization_members om
      WHERE om.user_id = auth.uid()
        AND om.organization_id = organization_id
        AND om.role = 'admin'
    )
  );
`;

  // Add foreign key from user tables to organizations
  for (const table of config.tables) {
    if (!table.name) continue;
    sql += `\n-- Tenant FK for ${table.name}`;
    sql += `\nALTER TABLE public.${table.name} ADD CONSTRAINT fk_${table.name}_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE;`;
  }

  return [{ path: "migrations/multi_tenancy.sql", content: sql, category: "sql" }];
}

// ─── Module: Centralized Logging ─────────────────────────────────────────────

function generateLoggingModule(_config: ProjectConfig): GeneratedFile[] {
  const sql = `-- ============================================================
-- Module: Centralized Logging & Analytics
-- SECURITY: Error logs and API metrics are admin-only.
-- Users can view their own activity logs.
-- ============================================================

CREATE TABLE public.activity_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  action TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_activity_logs_created_at ON public.activity_logs(created_at);
CREATE INDEX idx_activity_logs_user_id ON public.activity_logs(user_id);

CREATE POLICY "Users can view own activity"
  ON public.activity_logs FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all activity"
  ON public.activity_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Service can insert activity"
  ON public.activity_logs FOR INSERT TO service_role
  WITH CHECK (true);

CREATE TABLE public.error_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  error_type TEXT NOT NULL,
  message TEXT NOT NULL,
  stack_trace TEXT,
  context JSONB DEFAULT '{}',
  severity TEXT NOT NULL DEFAULT 'error',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_error_logs_created_at ON public.error_logs(created_at);
CREATE INDEX idx_error_logs_severity ON public.error_logs(severity);

-- SECURITY: Only admins can view error logs
CREATE POLICY "Admins can view error logs"
  ON public.error_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Service can insert error logs"
  ON public.error_logs FOR INSERT TO service_role
  WITH CHECK (true);

CREATE TABLE public.api_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  endpoint TEXT NOT NULL,
  method TEXT NOT NULL,
  status_code INT NOT NULL,
  duration_ms INT NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.api_metrics ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_api_metrics_created_at ON public.api_metrics(created_at);
CREATE INDEX idx_api_metrics_endpoint ON public.api_metrics(endpoint);

-- SECURITY: Only admins can view API metrics
CREATE POLICY "Admins can view api metrics"
  ON public.api_metrics FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Service can insert api metrics"
  ON public.api_metrics FOR INSERT TO service_role
  WITH CHECK (true);
`;

  const edgeFn = `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

/**
 * API Logger Middleware
 * 
 * Logs request duration, status codes, and endpoint usage.
 * Call this from your edge functions to track API performance.
 */
serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  try {
    const { endpoint, method, status_code, duration_ms, user_id, action, resource_type, resource_id, metadata, error_type, message, stack_trace, severity } = await req.json()

    // Log API metric
    if (endpoint && status_code) {
      await supabase.from('api_metrics').insert({
        endpoint,
        method: method || 'GET',
        status_code,
        duration_ms: duration_ms || 0,
        user_id: user_id || null,
      })
    }

    // Log activity
    if (action) {
      await supabase.from('activity_logs').insert({
        user_id: user_id || null,
        action,
        resource_type: resource_type || null,
        resource_id: resource_id || null,
        metadata: metadata || {},
      })
    }

    // Log error
    if (error_type) {
      await supabase.from('error_logs').insert({
        error_type,
        message: message || 'Unknown error',
        stack_trace: stack_trace || null,
        context: metadata || {},
        severity: severity || 'error',
      })
    }

    return new Response(JSON.stringify({ logged: true }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
`;

  return [
    { path: "migrations/logging.sql", content: sql, category: "sql" },
    { path: "functions/api-logger/index.ts", content: edgeFn, category: "functions" },
  ];
}

// ─── Module: Feature Flags ───────────────────────────────────────────────────

function generateFeatureFlagsModule(_config: ProjectConfig): GeneratedFile[] {
  const sql = `-- ============================================================
-- Module: Feature Flags
-- SECURITY: Only admins can create/update/delete flags.
-- All authenticated users can read flags.
-- ============================================================

CREATE TABLE public.feature_flags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT UNIQUE NOT NULL,
  description TEXT,
  enabled BOOLEAN NOT NULL DEFAULT false,
  metadata JSONB DEFAULT '{}',
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.feature_flags ENABLE ROW LEVEL SECURITY;

-- All authenticated users can check feature flags
CREATE POLICY "Authenticated can read flags"
  ON public.feature_flags FOR SELECT TO authenticated
  USING (true);

-- Only admins can manage feature flags
CREATE POLICY "Admins can insert flags"
  ON public.feature_flags FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can update flags"
  ON public.feature_flags FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can delete flags"
  ON public.feature_flags FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- Helper function to check if a feature is enabled
CREATE OR REPLACE FUNCTION public.is_feature_enabled(_flag_key TEXT)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(
    (SELECT enabled FROM public.feature_flags WHERE key = _flag_key),
    false
  )
$$;

-- Auto-update updated_at
CREATE TRIGGER update_feature_flags_updated_at
  BEFORE UPDATE ON public.feature_flags
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
`;

  return [{ path: "migrations/feature_flags.sql", content: sql, category: "sql" }];
}

// ─── Module: Background Jobs ─────────────────────────────────────────────────

function generateBackgroundJobsModule(_config: ProjectConfig): GeneratedFile[] {
  const sql = `-- ============================================================
-- Module: Background Jobs
-- SECURITY: Admins can manage all jobs.
-- Users can view their own jobs.
-- ============================================================

CREATE TYPE public.job_status AS ENUM ('pending', 'processing', 'failed', 'completed');

CREATE TABLE public.jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  payload JSONB DEFAULT '{}',
  status public.job_status NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 3,
  scheduled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  error TEXT,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_jobs_status_scheduled ON public.jobs(status, scheduled_at);
CREATE INDEX idx_jobs_created_by ON public.jobs(created_by);

-- Users can view their own jobs
CREATE POLICY "Users can view own jobs"
  ON public.jobs FOR SELECT TO authenticated
  USING (auth.uid() = created_by);

-- Admins can manage all jobs
CREATE POLICY "Admins can manage all jobs"
  ON public.jobs FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

-- Service role can manage jobs (for worker functions)
CREATE POLICY "Service can manage jobs"
  ON public.jobs FOR ALL TO service_role
  USING (true);

-- Claim a job atomically using FOR UPDATE SKIP LOCKED
CREATE OR REPLACE FUNCTION public.claim_job(_job_type TEXT DEFAULT NULL)
RETURNS SETOF public.jobs LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  claimed public.jobs;
BEGIN
  SELECT * INTO claimed
  FROM public.jobs
  WHERE status = 'pending'
    AND scheduled_at <= now()
    AND attempts < max_attempts
    AND (_job_type IS NULL OR type = _job_type)
  ORDER BY scheduled_at ASC
  LIMIT 1
  FOR UPDATE SKIP LOCKED;

  IF claimed.id IS NOT NULL THEN
    UPDATE public.jobs
    SET status = 'processing',
        started_at = now(),
        attempts = attempts + 1
    WHERE id = claimed.id;

    claimed.status := 'processing';
    claimed.started_at := now();
    claimed.attempts := claimed.attempts + 1;
    RETURN NEXT claimed;
  END IF;
  RETURN;
END;
$$;
`;

  const workerFn = `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

/**
 * Job Worker
 * 
 * Claims a pending job from the queue and processes it.
 * Uses FOR UPDATE SKIP LOCKED for safe concurrent processing.
 * Includes built-in retry logic via max_attempts.
 */
serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  try {
    const body = await req.json().catch(() => ({}))
    const jobType = body.job_type || null

    // Claim a job
    const { data: jobs, error: claimError } = await supabase
      .rpc('claim_job', { _job_type: jobType })

    if (claimError) throw claimError
    if (!jobs || jobs.length === 0) {
      return new Response(JSON.stringify({ message: 'No jobs available' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const job = jobs[0]

    try {
      // ─── Process job based on type ───
      // Add your job handlers here:
      switch (job.type) {
        case 'send_email':
          // await sendEmail(job.payload)
          break
        case 'generate_report':
          // await generateReport(job.payload)
          break
        default:
          console.log(\`Processing job type: \${job.type}\`, job.payload)
      }

      // Mark job as completed
      await supabase
        .from('jobs')
        .update({ status: 'completed', completed_at: new Date().toISOString() })
        .eq('id', job.id)

      return new Response(JSON.stringify({ processed: job.id, type: job.type }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    } catch (processingError) {
      // Mark job as failed (will be retried if attempts < max_attempts)
      const newStatus = job.attempts >= job.max_attempts ? 'failed' : 'pending'
      await supabase
        .from('jobs')
        .update({
          status: newStatus,
          error: processingError.message,
          started_at: null,
        })
        .eq('id', job.id)

      throw processingError
    }
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
`;

  return [
    { path: "migrations/background_jobs.sql", content: sql, category: "sql" },
    { path: "functions/job-worker/index.ts", content: workerFn, category: "functions" },
  ];
}

// ─── API Integration Framework ───────────────────────────────────────────────

function generateIntegrationFramework(): GeneratedFile[] {
  const baseClient = `/**
 * Base HTTP Client
 * Generic HTTP client with timeout, headers, and error handling.
 * 
 * Usage:
 *   const client = new BaseClient('https://api.example.com', {
 *     headers: { 'Authorization': 'Bearer ' + Deno.env.get('API_KEY') }
 *   });
 *   const data = await client.get('/users');
 */

export interface ClientOptions {
  headers?: Record<string, string>;
  timeout?: number; // ms, default 30000
}

export class BaseClient {
  private baseUrl: string;
  private headers: Record<string, string>;
  private timeout: number;

  constructor(baseUrl: string, options: ClientOptions = {}) {
    this.baseUrl = baseUrl.replace(/\\/$/, '');
    this.headers = {
      'Content-Type': 'application/json',
      ...options.headers,
    };
    this.timeout = options.timeout ?? 30000;
  }

  async request<T = unknown>(method: string, path: string, body?: unknown): Promise<T> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeout);

    try {
      const response = await fetch(\`\${this.baseUrl}\${path}\`, {
        method,
        headers: this.headers,
        body: body ? JSON.stringify(body) : undefined,
        signal: controller.signal,
      });

      if (!response.ok) {
        const errorBody = await response.text();
        throw new Error(\`HTTP \${response.status}: \${errorBody}\`);
      }

      return await response.json() as T;
    } finally {
      clearTimeout(timer);
    }
  }

  get<T = unknown>(path: string) { return this.request<T>('GET', path); }
  post<T = unknown>(path: string, body: unknown) { return this.request<T>('POST', path, body); }
  put<T = unknown>(path: string, body: unknown) { return this.request<T>('PUT', path, body); }
  delete<T = unknown>(path: string) { return this.request<T>('DELETE', path); }
}
`;

  const retryWrapper = `/**
 * Retry Wrapper
 * Exponential backoff retry logic for unreliable operations.
 * 
 * Usage:
 *   const result = await withRetry(() => client.get('/data'), { maxRetries: 3 });
 */

export interface RetryOptions {
  maxRetries?: number;       // default 3
  initialDelayMs?: number;   // default 1000
  maxDelayMs?: number;       // default 30000
  backoffFactor?: number;    // default 2
  retryOn?: (error: Error) => boolean; // custom retry condition
}

export async function withRetry<T>(
  fn: () => Promise<T>,
  options: RetryOptions = {}
): Promise<T> {
  const {
    maxRetries = 3,
    initialDelayMs = 1000,
    maxDelayMs = 30000,
    backoffFactor = 2,
    retryOn = () => true,
  } = options;

  let lastError: Error;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error instanceof Error ? error : new Error(String(error));

      if (attempt === maxRetries || !retryOn(lastError)) {
        throw lastError;
      }

      const delay = Math.min(initialDelayMs * Math.pow(backoffFactor, attempt), maxDelayMs);
      const jitter = delay * (0.5 + Math.random() * 0.5);
      await new Promise((resolve) => setTimeout(resolve, jitter));
    }
  }

  throw lastError!;
}
`;

  const webhookHandler = `/**
 * Webhook Handler
 * HMAC-SHA256 signature verification for incoming webhooks.
 * 
 * Usage:
 *   const isValid = await verifyWebhookSignature(requestBody, signatureHeader, secret);
 */

export async function verifyWebhookSignature(
  payload: string,
  signature: string,
  secret: string
): Promise<boolean> {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );

  const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(payload));
  const computed = Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');

  // Constant-time comparison to prevent timing attacks
  if (computed.length !== signature.length) return false;
  let result = 0;
  for (let i = 0; i < computed.length; i++) {
    result |= computed.charCodeAt(i) ^ signature.charCodeAt(i);
  }
  return result === 0;
}

/**
 * Example webhook handler edge function pattern:
 * 
 * serve(async (req) => {
 *   const body = await req.text();
 *   const signature = req.headers.get('x-webhook-signature') || '';
 *   const secret = Deno.env.get('WEBHOOK_SECRET')!;
 *   
 *   if (!await verifyWebhookSignature(body, signature, secret)) {
 *     return new Response('Invalid signature', { status: 401 });
 *   }
 *   
 *   const payload = JSON.parse(body);
 *   // Process webhook...
 * });
 */
`;

  const exampleIntegration = `/**
 * Example Integration
 * Shows how to combine BaseClient + RetryWrapper for a real API.
 * Copy and modify this for your integrations.
 */

import { BaseClient } from './base-client.ts';
import { withRetry } from './retry-wrapper.ts';

// Initialize client with env-based configuration
const apiClient = new BaseClient('https://api.example.com/v1', {
  headers: {
    'Authorization': \`Bearer \${Deno.env.get('EXAMPLE_API_KEY') || ''}\`,
  },
  timeout: 15000,
});

// Typed response interfaces
interface ExampleUser {
  id: string;
  name: string;
  email: string;
}

// API methods with retry
export async function getUser(userId: string): Promise<ExampleUser> {
  return withRetry(
    () => apiClient.get<ExampleUser>(\`/users/\${userId}\`),
    { maxRetries: 2, initialDelayMs: 500 }
  );
}

export async function createUser(data: Omit<ExampleUser, 'id'>): Promise<ExampleUser> {
  return withRetry(
    () => apiClient.post<ExampleUser>('/users', data),
    {
      maxRetries: 1,
      // Only retry on network errors, not validation errors
      retryOn: (error) => !error.message.includes('HTTP 4'),
    }
  );
}

export async function listUsers(): Promise<ExampleUser[]> {
  return withRetry(() => apiClient.get<ExampleUser[]>('/users'));
}
`;

  return [
    { path: "integrations/base-client.ts", content: baseClient, category: "functions" },
    { path: "integrations/retry-wrapper.ts", content: retryWrapper, category: "functions" },
    { path: "integrations/webhook-handler.ts", content: webhookHandler, category: "functions" },
    { path: "integrations/example-integration.ts", content: exampleIntegration, category: "functions" },
  ];
}

// ─── Seed Data ───────────────────────────────────────────────────────────────

function generateSeed(config: ProjectConfig): string {
  const lines: string[] = ["-- Seed Data", ""];
  for (const table of config.tables) {
    if (!table.name || table.columns.length === 0) continue;
    const cols = table.columns.filter((c) => !c.isPrimary && c.name !== "created_at" && c.name !== "updated_at" && c.name !== "deleted_at");
    if (cols.length === 0) continue;
    const colNames = cols.map((c) => c.name).join(", ");
    const sampleValues = cols.map((c) => {
      switch (c.type) {
        case "text": case "varchar": return `'sample_${c.name}'`;
        case "int": case "bigint": case "serial": case "bigserial": return "1";
        case "float": return "1.0";
        case "boolean": return "true";
        case "uuid": return "gen_random_uuid()";
        case "timestamp": case "timestamptz": case "date": return "now()";
        case "jsonb": case "json": return "'{}'";
        default: return "NULL";
      }
    }).join(", ");
    lines.push(`INSERT INTO public.${table.name} (${colNames}) VALUES (${sampleValues});`);
  }
  return lines.join("\n");
}

// ─── Edge Functions ──────────────────────────────────────────────────────────

function generateEdgeFunction(tableName: string, config: ProjectConfig): string {
  return `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  const url = new URL(req.url)
  const method = req.method

  try {
    if (method === 'GET') {
      const page = parseInt(url.searchParams.get('page') || '1')
      const limit = parseInt(url.searchParams.get('limit') || '20')
      const offset = (page - 1) * limit

      const { data, error, count } = await supabase
        .from('${tableName}')
        .select('*', { count: 'exact' })
        .range(offset, offset + limit - 1)

      if (error) throw error
      return new Response(JSON.stringify({ data, count, page, limit }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'POST') {
      const body = await req.json()
      const { data, error } = await supabase.from('${tableName}').insert(body).select().single()
      if (error) throw error
      return new Response(JSON.stringify(data), {
        status: 201,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'PUT' || method === 'PATCH') {
      const id = url.searchParams.get('id')
      if (!id) throw new Error('Missing id parameter')
      const body = await req.json()
      const { data, error } = await supabase.from('${tableName}').update(body).eq('id', id).select().single()
      if (error) throw error
      return new Response(JSON.stringify(data), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'DELETE') {
      const id = url.searchParams.get('id')
      if (!id) throw new Error('Missing id parameter')
      ${config.features.softDelete
        ? `const { error } = await supabase.from('${tableName}').update({ deleted_at: new Date().toISOString() }).eq('id', id)`
        : `const { error } = await supabase.from('${tableName}').delete().eq('id', id)`
      }
      if (error) throw error
      return new Response(JSON.stringify({ success: true }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    return new Response('Method not allowed', { status: 405, headers: corsHeaders })
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })
  }
})
`;
}

// ─── Frontend Files (unchanged) ──────────────────────────────────────────────

function generateFrontendFiles(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  files.push({
    path: "frontend/src/App.tsx",
    content: `import { BrowserRouter, Routes, Route } from 'react-router-dom';
${config.frontendOptions.loginSignup ? "import Login from './pages/Login';\nimport Signup from './pages/Signup';" : ""}
${config.frontendOptions.roleDashboards ? "import Dashboard from './pages/Dashboard';" : ""}
${config.frontendOptions.crudPages ? config.tables.map((t) => `import ${capitalize(t.name)}List from './pages/${capitalize(t.name)}List';`).join("\n") : ""}

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={${config.frontendOptions.roleDashboards ? "<Dashboard />" : "<div>Home</div>"}} />
${config.frontendOptions.loginSignup ? '        <Route path="/login" element={<Login />} />\n        <Route path="/signup" element={<Signup />} />' : ""}
${config.frontendOptions.crudPages ? config.tables.map((t) => `        <Route path="/${t.name}" element={<${capitalize(t.name)}List />} />`).join("\n") : ""}
      </Routes>
    </BrowserRouter>
  );
}`,
    category: "frontend",
  });

  if (config.frontendOptions.loginSignup) {
    files.push({
      path: "frontend/src/pages/Login.tsx",
      content: `import { useState } from 'react';
import { supabase } from '../lib/supabase';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) alert(error.message);
    else window.location.href = '/';
  };

  return (
    <div className="min-h-screen flex items-center justify-center">
      <form onSubmit={handleLogin} className="w-full max-w-md space-y-4 p-8">
        <h1 className="text-2xl font-bold">Sign In</h1>
        <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="w-full border p-2 rounded" required />
        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" className="w-full border p-2 rounded" required />
        <button type="submit" className="w-full bg-primary text-white p-2 rounded">Sign In</button>
      </form>
    </div>
  );
}`,
      category: "frontend",
    });
  }

  if (config.frontendOptions.crudPages) {
    for (const table of config.tables) {
      if (!table.name) continue;
      files.push({
        path: `frontend/src/pages/${capitalize(table.name)}List.tsx`,
        content: `import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

export default function ${capitalize(table.name)}List() {
  const [items, setItems] = useState<any[]>([]);

  useEffect(() => {
    supabase.from('${table.name}').select('*').then(({ data }) => setItems(data || []));
  }, []);

  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold mb-4">${capitalize(table.name)}</h1>
      <div className="space-y-2">
        {items.map((item) => (
          <div key={item.id} className="border p-4 rounded">
            <pre className="text-sm">{JSON.stringify(item, null, 2)}</pre>
          </div>
        ))}
      </div>
    </div>
  );
}`,
        category: "frontend",
      });
    }
  }

  return files;
}

// ─── Documentation ───────────────────────────────────────────────────────────

function generateReadme(config: ProjectConfig): string {
  const allFeatures: { key: keyof typeof config.features; label: string }[] = [
    { key: "auth", label: "Authentication (email/password)" },
    { key: "timestamps", label: "Auto timestamps" },
    { key: "softDelete", label: "Soft delete" },
    { key: "auditLogs", label: "Audit logging" },
    { key: "notifications", label: "Notification triggers" },
    { key: "fileUploads", label: "File uploads" },
    { key: "searchPagination", label: "Search & pagination" },
    { key: "rateLimiting", label: "Rate limiting" },
    { key: "multiTenancy", label: "Multi-tenancy (organizations)" },
    { key: "apiIntegrations", label: "API integration framework" },
    { key: "logging", label: "Centralized logging & analytics" },
    { key: "featureFlags", label: "Feature flags" },
    { key: "backgroundJobs", label: "Background job queue" },
  ];

  const enabledFeatures = allFeatures.filter((f) => config.features[f.key]);

  let readme = `# ${config.projectName}

${config.description || "Generated by Supabase Project Factory"}

## Architecture Overview

This project uses a modular architecture. Each feature is an independent module that generates its own migrations, RLS policies, and helper functions.

### Enabled Modules

${enabledFeatures.map((f) => `- ✅ ${f.label}`).join("\n")}

## Setup

1. Install Supabase CLI: \`npm install -g supabase\`
2. Initialize project: \`supabase init\`
3. Copy migration files to \`supabase/migrations/\`
4. Apply migrations: \`supabase db push\`
5. Deploy edge functions: \`supabase functions deploy\`
6. Copy \`.env.example\` to \`.env\` and fill in values
7. Start locally: \`supabase start\`

## Structure

- \`migrations/\` — Versioned SQL migrations (schema, roles, RLS, modules)
- \`functions/\` — Edge function stubs for API endpoints
${config.features.apiIntegrations ? "- `integrations/` — HTTP client, retry logic, webhook templates\n" : ""}\
${config.frontendOptions.enabled ? "- `frontend/` — React + Tailwind frontend skeleton\n" : ""}\
- \`seed.sql\` — Sample data for testing

## Tables

${config.tables.map((t) => `- \`${t.name}\` (${t.columns.length} columns)`).join("\n")}

## Roles

${config.roles.map((r) => `- \`${r.name}\``).join("\n") || "No roles defined"}
`;

  if (config.features.rateLimiting) {
    readme += `
## Rate Limiting

Rate limits are configured in the \`api_rate_limits\` table. Each endpoint can have custom limits:
- \`max_requests\`: Maximum requests per window (default: 100)
- \`window_seconds\`: Time window in seconds (default: 60)
- \`role\`: Which role this limit applies to

The \`rate-limiter\` edge function checks limits by user ID or IP address.
`;
  }

  if (config.features.multiTenancy) {
    readme += `
## Multi-Tenancy

Tenant isolation is enforced via RLS policies. Every user table includes an \`organization_id\` column.

Key functions:
- \`is_tenant_member(org_id)\`: Check if user belongs to an org
- \`current_organization()\`: Get the user's current org ID

Organizations are managed via the \`organizations\` and \`organization_members\` tables.
`;
  }

  if (config.features.featureFlags) {
    readme += `
## Feature Flags

Feature flags are stored in the \`feature_flags\` table. Use \`is_feature_enabled('flag_key')\` in your SQL or RLS policies.

Only admins can create/update/delete flags. All authenticated users can read them.
`;
  }

  readme += `
## Security Notes

- All tables have RLS enabled by default (deny-all without explicit policies)
- Roles are stored in a separate \`user_roles\` table (not on profiles) to prevent escalation
- The \`has_role()\` function uses SECURITY DEFINER to avoid recursive RLS
- All generated SQL includes security decision comments

## Deployment Checklist

- [ ] Copy all migration files to \`supabase/migrations/\`
- [ ] Run \`supabase db push\` to apply schema
- [ ] Deploy edge functions with \`supabase functions deploy\`
- [ ] Set environment variables from \`.env.example\`
- [ ] Create initial admin user and assign 'admin' role
- [ ] Verify RLS policies are working as expected
- [ ] Run seed data if needed: \`psql -f seed.sql\`
`;

  return readme;
}

function generateApiDocs(config: ProjectConfig): string {
  const lines: string[] = [`# API Documentation — ${config.projectName}`, ""];

  for (const ep of config.apiEndpoints) {
    if (!ep.crud) continue;
    lines.push(`## ${ep.table}`, "");
    lines.push(`### GET /functions/v1/${ep.table}`);
    lines.push(`List all ${ep.table}. Supports \`?page=1&limit=20\`.`, "");
    lines.push(`### POST /functions/v1/${ep.table}`);
    lines.push(`Create a new ${ep.table} record.`, "");
    lines.push(`### PUT /functions/v1/${ep.table}?id=<uuid>`);
    lines.push(`Update a ${ep.table} record.`, "");
    lines.push(`### DELETE /functions/v1/${ep.table}?id=<uuid>`);
    lines.push(`Delete a ${ep.table} record.`, "");
  }

  if (config.features.rateLimiting) {
    lines.push("## Rate Limiter", "");
    lines.push("### POST /functions/v1/rate-limiter");
    lines.push("Check rate limit before processing a request.", "");
    lines.push("Body: `{ endpoint, user_id?, ip_address? }`", "");
    lines.push("Returns `{ allowed, remaining }` or `429` with `Retry-After` header.", "");
  }

  if (config.features.backgroundJobs) {
    lines.push("## Job Worker", "");
    lines.push("### POST /functions/v1/job-worker");
    lines.push("Claims and processes the next pending job.", "");
    lines.push("Body: `{ job_type? }` — optional filter by job type.", "");
  }

  if (config.features.logging) {
    lines.push("## API Logger", "");
    lines.push("### POST /functions/v1/api-logger");
    lines.push("Log API metrics, activity, or errors.", "");
    lines.push("Body: `{ endpoint?, status_code?, duration_ms?, action?, error_type?, message? }`", "");
  }

  return lines.join("\n");
}

function generateArchitectureDocs(config: ProjectConfig): string {
  const modules: string[] = [];

  if (config.features.auth) modules.push("- **Authentication**: Email/password auth via Supabase Auth");
  if (config.features.timestamps) modules.push("- **Timestamps**: Auto `created_at`/`updated_at` via trigger");
  if (config.features.softDelete) modules.push("- **Soft Delete**: `deleted_at` column + `_active` views");
  if (config.features.auditLogs) modules.push("- **Audit Logs**: Trigger-based change tracking on all tables");
  if (config.features.fileUploads) modules.push("- **File Uploads**: Storage bucket with user-scoped RLS");
  if (config.features.rateLimiting) modules.push("- **Rate Limiting**: Per-endpoint limits with IP/user tracking + edge function middleware");
  if (config.features.multiTenancy) modules.push("- **Multi-Tenancy**: Organization-based isolation with `is_tenant_member()` helper");
  if (config.features.apiIntegrations) modules.push("- **API Integrations**: Base HTTP client, retry wrapper, webhook verification");
  if (config.features.logging) modules.push("- **Centralized Logging**: Activity logs, error logs, API metrics + logger edge function");
  if (config.features.featureFlags) modules.push("- **Feature Flags**: Admin-managed flags with `is_feature_enabled()` helper");
  if (config.features.backgroundJobs) modules.push("- **Background Jobs**: Queue with `claim_job()` (SKIP LOCKED) + worker edge function");

  return `# Architecture — ${config.projectName}

## Module System

Each module is independent and generates its own:
- SQL migration file (numbered for ordering)
- RLS policies (secure by default)
- Helper functions (SECURITY DEFINER where needed)
- Edge functions (where applicable)
- Documentation entries

## Enabled Modules

${modules.join("\n")}

## Migration Order

\`\`\`
migrations/001_core.sql          — Tables, indexes, constraints
migrations/002_roles.sql         — Role enum, user_roles table, has_role()
migrations/003_rls.sql           — Per-role RLS policies
migrations/004_*.sql             — Optional module migrations
seed.sql                         — Sample data
\`\`\`

## Security Model

1. **Deny by default**: All tables have RLS enabled. No access without explicit policies.
2. **Role separation**: Roles stored in \`user_roles\` table (not on profiles).
3. **No recursion**: \`has_role()\` uses SECURITY DEFINER to prevent RLS recursion.
4. **Tenant isolation**: Multi-tenancy uses \`is_tenant_member()\` for org-scoped access.
5. **Service role**: Edge functions use service role for privileged operations only.
`;
}

function generateEnvExample(config: ProjectConfig): string {
  let env = `# ============================================================
# Environment Variables
# Copy this file to .env and fill in the values.
# ============================================================

# Supabase (required)
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
`;

  if (config.features.apiIntegrations) {
    env += `
# API Integrations
EXAMPLE_API_KEY=your-api-key
WEBHOOK_SECRET=your-webhook-secret
`;
  }

  return env;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
