import { ProjectConfig } from "@/types/project";

export interface GeneratedFile {
  path: string;
  content: string;
  category: "sql" | "functions" | "frontend" | "docs";
}

export function generateProject(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // 1. SQL Migration
  files.push({ path: "migrations/001_schema.sql", content: generateSchema(config), category: "sql" });

  // 2. RLS Policies
  if (config.roles.length > 0) {
    files.push({ path: "migrations/002_rls.sql", content: generateRLS(config), category: "sql" });
  }

  // 3. Roles setup
  if (config.roles.length > 0) {
    files.push({ path: "migrations/003_roles.sql", content: generateRolesSetup(config), category: "sql" });
  }

  // 4. Optional features
  if (config.features.auditLogs) {
    files.push({ path: "migrations/004_audit.sql", content: generateAuditLog(config), category: "sql" });
  }
  if (config.features.softDelete) {
    files.push({ path: "migrations/005_soft_delete.sql", content: generateSoftDelete(config), category: "sql" });
  }
  if (config.features.fileUploads) {
    files.push({ path: "migrations/006_storage.sql", content: generateStorage(config), category: "sql" });
  }

  // 5. Seed data
  files.push({ path: "seed.sql", content: generateSeed(config), category: "sql" });

  // 6. Edge functions
  config.apiEndpoints.filter((e) => e.crud).forEach((ep) => {
    files.push({
      path: `functions/${ep.table}/index.ts`,
      content: generateEdgeFunction(ep.table, config),
      category: "functions",
    });
  });

  // 7. Frontend (optional)
  if (config.frontendOptions.enabled) {
    files.push(...generateFrontendFiles(config));
  }

  // 8. Docs
  files.push({ path: "README.md", content: generateReadme(config), category: "docs" });
  files.push({ path: "API.md", content: generateApiDocs(config), category: "docs" });

  return files;
}

function generateSchema(config: ProjectConfig): string {
  const lines: string[] = [
    "-- Generated by Supabase Project Factory",
    `-- Project: ${config.projectName}`,
    "",
  ];

  // Relationships: generate junction tables for N:N
  const junctionTables: string[] = [];

  for (const table of config.tables) {
    if (!table.name) continue;
    lines.push(`CREATE TABLE public.${table.name} (`);
    const colDefs: string[] = [];

    for (const col of table.columns) {
      if (!col.name) continue;
      let def = `  ${col.name} ${col.type.toUpperCase()}`;
      if (col.isPrimary) def += " PRIMARY KEY";
      if (col.type === "uuid" && col.isPrimary) def += " DEFAULT gen_random_uuid()";
      if (col.isRequired && !col.isPrimary) def += " NOT NULL";
      if (col.isUnique && !col.isPrimary) def += " UNIQUE";
      if (col.defaultValue) def += ` DEFAULT ${col.defaultValue}`;
      colDefs.push(def);
    }

    // Add user_id for auth
    if (config.features.auth && !table.columns.some((c) => c.name === "user_id")) {
      colDefs.push("  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL");
    }

    // Timestamps
    if (config.features.timestamps) {
      if (!table.columns.some((c) => c.name === "created_at"))
        colDefs.push("  created_at TIMESTAMPTZ NOT NULL DEFAULT now()");
      if (!table.columns.some((c) => c.name === "updated_at"))
        colDefs.push("  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()");
    }

    // Soft delete
    if (config.features.softDelete) {
      colDefs.push("  deleted_at TIMESTAMPTZ");
    }

    lines.push(colDefs.join(",\n"));
    lines.push(");");
    lines.push("");

    // Indexes
    for (const col of table.columns) {
      if (col.isIndexed && !col.isPrimary) {
        lines.push(`CREATE INDEX idx_${table.name}_${col.name} ON public.${table.name}(${col.name});`);
      }
    }

    // Enable RLS
    lines.push(`ALTER TABLE public.${table.name} ENABLE ROW LEVEL SECURITY;`);
    lines.push("");
  }

  // Relationships: foreign keys for 1:1 and 1:N
  for (const rel of config.relationships) {
    if (rel.type === "1:1" || rel.type === "1:N") {
      lines.push(
        `ALTER TABLE public.${rel.to.table} ADD COLUMN ${rel.from.table}_id UUID REFERENCES public.${rel.from.table}(id) ON DELETE CASCADE;`
      );
    } else if (rel.type === "N:N") {
      const jt = `${rel.from.table}_${rel.to.table}`;
      junctionTables.push(jt);
      lines.push(`CREATE TABLE public.${jt} (`);
      lines.push(`  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),`);
      lines.push(`  ${rel.from.table}_id UUID REFERENCES public.${rel.from.table}(id) ON DELETE CASCADE NOT NULL,`);
      lines.push(`  ${rel.to.table}_id UUID REFERENCES public.${rel.to.table}(id) ON DELETE CASCADE NOT NULL,`);
      lines.push(`  UNIQUE(${rel.from.table}_id, ${rel.to.table}_id)`);
      lines.push(`);`);
      lines.push(`ALTER TABLE public.${jt} ENABLE ROW LEVEL SECURITY;`);
      lines.push("");
    }
  }

  // Timestamp trigger
  if (config.features.timestamps) {
    lines.push(`
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
`);
    for (const table of config.tables) {
      if (!table.name) continue;
      lines.push(
        `CREATE TRIGGER update_${table.name}_updated_at BEFORE UPDATE ON public.${table.name} FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();`
      );
    }
  }

  return lines.join("\n");
}

function generateRolesSetup(config: ProjectConfig): string {
  const roleNames = config.roles.map((r) => `'${r.name}'`).join(", ");
  return `-- Role-Based Access Control Setup
CREATE TYPE public.app_role AS ENUM (${roleNames});

CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  UNIQUE (user_id, role)
);

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Security definer function to check roles (avoids RLS recursion)
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

-- Allow authenticated users to read their own roles
CREATE POLICY "Users can view own roles"
  ON public.user_roles FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Only admins can manage roles
CREATE POLICY "Admins can manage roles"
  ON public.user_roles FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));
`;
}

function generateRLS(config: ProjectConfig): string {
  const lines: string[] = ["-- Row Level Security Policies", ""];

  for (const role of config.roles) {
    if (!role.name) continue;
    for (const table of config.tables) {
      if (!table.name) continue;
      const perms = role.permissions[table.name];
      if (!perms) continue;

      if (perms.select) {
        lines.push(`CREATE POLICY "${role.name}_select_${table.name}"`);
        lines.push(`  ON public.${table.name} FOR SELECT TO authenticated`);
        lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${config.features.auth ? " OR auth.uid() = user_id" : ""});`);
        lines.push("");
      }
      if (perms.insert) {
        lines.push(`CREATE POLICY "${role.name}_insert_${table.name}"`);
        lines.push(`  ON public.${table.name} FOR INSERT TO authenticated`);
        lines.push(`  WITH CHECK (public.has_role(auth.uid(), '${role.name}')${config.features.auth ? " OR auth.uid() = user_id" : ""});`);
        lines.push("");
      }
      if (perms.update) {
        lines.push(`CREATE POLICY "${role.name}_update_${table.name}"`);
        lines.push(`  ON public.${table.name} FOR UPDATE TO authenticated`);
        lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${config.features.auth ? " OR auth.uid() = user_id" : ""});`);
        lines.push("");
      }
      if (perms.delete) {
        lines.push(`CREATE POLICY "${role.name}_delete_${table.name}"`);
        lines.push(`  ON public.${table.name} FOR DELETE TO authenticated`);
        lines.push(`  USING (public.has_role(auth.uid(), '${role.name}')${config.features.auth ? " OR auth.uid() = user_id" : ""});`);
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

function generateAuditLog(config: ProjectConfig): string {
  let sql = `-- Audit Logging
CREATE TABLE public.audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name TEXT NOT NULL,
  record_id TEXT,
  action TEXT NOT NULL,
  old_data JSONB,
  new_data JSONB,
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view audit logs"
  ON public.audit_logs FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.audit_trigger_fn()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, old_data, user_id)
    VALUES (TG_TABLE_NAME, OLD.id::TEXT, 'DELETE', to_jsonb(OLD), auth.uid());
    RETURN OLD;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, old_data, new_data, user_id)
    VALUES (TG_TABLE_NAME, NEW.id::TEXT, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW), auth.uid());
    RETURN NEW;
  ELSIF TG_OP = 'INSERT' THEN
    INSERT INTO public.audit_logs (table_name, record_id, action, new_data, user_id)
    VALUES (TG_TABLE_NAME, NEW.id::TEXT, 'INSERT', to_jsonb(NEW), auth.uid());
    RETURN NEW;
  END IF;
END;
$$;
`;

  for (const table of config.tables) {
    if (!table.name) continue;
    sql += `\nCREATE TRIGGER audit_${table.name} AFTER INSERT OR UPDATE OR DELETE ON public.${table.name} FOR EACH ROW EXECUTE FUNCTION public.audit_trigger_fn();`;
  }

  return sql;
}

function generateSoftDelete(config: ProjectConfig): string {
  const lines: string[] = ["-- Soft Delete Views"];
  for (const table of config.tables) {
    if (!table.name) continue;
    lines.push(`CREATE VIEW public.${table.name}_active AS SELECT * FROM public.${table.name} WHERE deleted_at IS NULL;`);
  }
  return lines.join("\n");
}

function generateStorage(config: ProjectConfig): string {
  return `-- File Storage Setup
INSERT INTO storage.buckets (id, name, public) VALUES ('uploads', 'uploads', false);

CREATE POLICY "Users can upload files"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);

CREATE POLICY "Users can view own files"
  ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);

CREATE POLICY "Users can delete own files"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'uploads' AND auth.uid()::TEXT = (storage.foldername(name))[1]);
`;
}

function generateSeed(config: ProjectConfig): string {
  const lines: string[] = ["-- Seed Data", ""];
  for (const table of config.tables) {
    if (!table.name || table.columns.length === 0) continue;
    const cols = table.columns.filter((c) => !c.isPrimary && c.name !== "created_at" && c.name !== "updated_at" && c.name !== "deleted_at");
    if (cols.length === 0) continue;
    const colNames = cols.map((c) => c.name).join(", ");
    const sampleValues = cols.map((c) => {
      switch (c.type) {
        case "text": case "varchar": return `'sample_${c.name}'`;
        case "int": case "bigint": case "serial": case "bigserial": return "1";
        case "float": return "1.0";
        case "boolean": return "true";
        case "uuid": return "gen_random_uuid()";
        case "timestamp": case "timestamptz": case "date": return "now()";
        case "jsonb": case "json": return "'{}'";
        default: return "NULL";
      }
    }).join(", ");
    lines.push(`INSERT INTO public.${table.name} (${colNames}) VALUES (${sampleValues});`);
  }
  return lines.join("\n");
}

function generateEdgeFunction(tableName: string, config: ProjectConfig): string {
  return `import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  )

  const url = new URL(req.url)
  const method = req.method

  try {
    if (method === 'GET') {
      // List with optional pagination
      const page = parseInt(url.searchParams.get('page') || '1')
      const limit = parseInt(url.searchParams.get('limit') || '20')
      const offset = (page - 1) * limit

      const { data, error, count } = await supabase
        .from('${tableName}')
        .select('*', { count: 'exact' })
        .range(offset, offset + limit - 1)

      if (error) throw error
      return new Response(JSON.stringify({ data, count, page, limit }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'POST') {
      const body = await req.json()
      const { data, error } = await supabase.from('${tableName}').insert(body).select().single()
      if (error) throw error
      return new Response(JSON.stringify(data), {
        status: 201,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'PUT' || method === 'PATCH') {
      const id = url.searchParams.get('id')
      if (!id) throw new Error('Missing id parameter')
      const body = await req.json()
      const { data, error } = await supabase.from('${tableName}').update(body).eq('id', id).select().single()
      if (error) throw error
      return new Response(JSON.stringify(data), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    if (method === 'DELETE') {
      const id = url.searchParams.get('id')
      if (!id) throw new Error('Missing id parameter')
      ${config.features.softDelete
        ? `const { error } = await supabase.from('${tableName}').update({ deleted_at: new Date().toISOString() }).eq('id', id)`
        : `const { error } = await supabase.from('${tableName}').delete().eq('id', id)`
      }
      if (error) throw error
      return new Response(JSON.stringify({ success: true }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      })
    }

    return new Response('Method not allowed', { status: 405, headers: corsHeaders })
  } catch (error) {
    return new Response(JSON.stringify({ error: error.message }), {
      status: 400,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    })
  }
})
`;
}

function generateFrontendFiles(config: ProjectConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // App shell
  files.push({
    path: "frontend/src/App.tsx",
    content: `import { BrowserRouter, Routes, Route } from 'react-router-dom';
${config.frontendOptions.loginSignup ? "import Login from './pages/Login';\nimport Signup from './pages/Signup';" : ""}
${config.frontendOptions.roleDashboards ? "import Dashboard from './pages/Dashboard';" : ""}
${config.frontendOptions.crudPages ? config.tables.map((t) => `import ${capitalize(t.name)}List from './pages/${capitalize(t.name)}List';`).join("\n") : ""}

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={${config.frontendOptions.roleDashboards ? "<Dashboard />" : "<div>Home</div>"}} />
${config.frontendOptions.loginSignup ? '        <Route path="/login" element={<Login />} />\n        <Route path="/signup" element={<Signup />} />' : ""}
${config.frontendOptions.crudPages ? config.tables.map((t) => `        <Route path="/${t.name}" element={<${capitalize(t.name)}List />} />`).join("\n") : ""}
      </Routes>
    </BrowserRouter>
  );
}`,
    category: "frontend",
  });

  if (config.frontendOptions.loginSignup) {
    files.push({
      path: "frontend/src/pages/Login.tsx",
      content: `import { useState } from 'react';
import { supabase } from '../lib/supabase';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    const { error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) alert(error.message);
    else window.location.href = '/';
  };

  return (
    <div className="min-h-screen flex items-center justify-center">
      <form onSubmit={handleLogin} className="w-full max-w-md space-y-4 p-8">
        <h1 className="text-2xl font-bold">Sign In</h1>
        <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="w-full border p-2 rounded" required />
        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" className="w-full border p-2 rounded" required />
        <button type="submit" className="w-full bg-primary text-white p-2 rounded">Sign In</button>
      </form>
    </div>
  );
}`,
      category: "frontend",
    });
  }

  // CRUD pages
  if (config.frontendOptions.crudPages) {
    for (const table of config.tables) {
      if (!table.name) continue;
      files.push({
        path: `frontend/src/pages/${capitalize(table.name)}List.tsx`,
        content: `import { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

export default function ${capitalize(table.name)}List() {
  const [items, setItems] = useState<any[]>([]);

  useEffect(() => {
    supabase.from('${table.name}').select('*').then(({ data }) => setItems(data || []));
  }, []);

  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold mb-4">${capitalize(table.name)}</h1>
      <div className="space-y-2">
        {items.map((item) => (
          <div key={item.id} className="border p-4 rounded">
            <pre className="text-sm">{JSON.stringify(item, null, 2)}</pre>
          </div>
        ))}
      </div>
    </div>
  );
}`,
        category: "frontend",
      });
    }
  }

  return files;
}

function generateReadme(config: ProjectConfig): string {
  return `# ${config.projectName}

${config.description || "Generated by Supabase Project Factory"}

## Setup

1. Install Supabase CLI: \`npm install -g supabase\`
2. Initialize project: \`supabase init\`
3. Apply migrations: \`supabase db push\`
4. Start locally: \`supabase start\`

## Structure

- \`migrations/\` — SQL schema, RLS policies, roles, triggers
- \`functions/\` — Edge function stubs for API endpoints
${config.frontendOptions.enabled ? "- `frontend/` — React + Tailwind frontend skeleton" : ""}
- \`seed.sql\` — Sample data for testing

## Features

${config.features.auth ? "- ✅ Authentication (email/password)\n" : ""}${config.features.timestamps ? "- ✅ Auto timestamps\n" : ""}${config.features.softDelete ? "- ✅ Soft delete\n" : ""}${config.features.auditLogs ? "- ✅ Audit logging\n" : ""}${config.features.notifications ? "- ✅ Notification triggers\n" : ""}${config.features.fileUploads ? "- ✅ File uploads\n" : ""}${config.features.searchPagination ? "- ✅ Search & pagination\n" : ""}

## Tables

${config.tables.map((t) => `- \`${t.name}\` (${t.columns.length} columns)`).join("\n")}

## Roles

${config.roles.map((r) => `- \`${r.name}\``).join("\n") || "No roles defined"}

## Customization

- Add tables: Create new migration files in \`migrations/\`
- Modify RLS: Edit \`migrations/002_rls.sql\`
- Add roles: Update the \`app_role\` enum and \`003_roles.sql\`
`;
}

function generateApiDocs(config: ProjectConfig): string {
  const lines: string[] = [`# API Documentation — ${config.projectName}`, ""];

  for (const ep of config.apiEndpoints) {
    if (!ep.crud) continue;
    lines.push(`## ${ep.table}`, "");
    lines.push(`### GET /functions/v1/${ep.table}`);
    lines.push(`List all ${ep.table}. Supports \`?page=1&limit=20\`.`, "");
    lines.push(`### POST /functions/v1/${ep.table}`);
    lines.push(`Create a new ${ep.table} record.`, "");
    lines.push(`### PUT /functions/v1/${ep.table}?id=<uuid>`);
    lines.push(`Update a ${ep.table} record.`, "");
    lines.push(`### DELETE /functions/v1/${ep.table}?id=<uuid>`);
    lines.push(`Delete a ${ep.table} record.`, "");
  }

  return lines.join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
