import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import { Database, Shield, Zap, Code, ArrowRight, Terminal, Layers, Lock } from "lucide-react";

const features = [
  { icon: Database, title: "Schema Generator", desc: "Tables, columns, indexes, and foreign keys from a visual builder" },
  { icon: Shield, title: "RLS Policies", desc: "Auto-configured row-level security per role with the has_role pattern" },
  { icon: Zap, title: "Triggers & Functions", desc: "Audit logs, timestamps, notifications — toggle on/off" },
  { icon: Code, title: "Frontend Skeleton", desc: "Optional React + Tailwind pages with auth, dashboards, CRUD" },
  { icon: Lock, title: "RBAC", desc: "Define roles, assign permissions per table via a visual matrix" },
  { icon: Layers, title: "Export & Deploy", desc: "Download ZIP or copy files — deploy with one CLI command" },
];

const Index = () => {
  return (
    <div className="min-h-screen bg-background dark">
      {/* Nav */}
      <nav className="border-b border-border/50 backdrop-blur-sm sticky top-0 z-50 bg-background/80">
        <div className="container mx-auto flex items-center justify-between h-16 px-4">
          <div className="flex items-center gap-2">
            <Terminal className="h-6 w-6 text-primary" />
            <span className="text-lg font-bold font-mono text-foreground">supabase.factory</span>
          </div>
          <div className="flex items-center gap-3">
            <Link to="/editor">
              <Button variant="ghost" size="sm" className="text-foreground/80 hover:text-foreground">Editor</Button>
            </Link>
            <Link to="/auth">
              <Button variant="ghost" size="sm" className="text-foreground/80 hover:text-foreground">Sign In</Button>
            </Link>
            <Link to="/auth?mode=signup">
              <Button size="sm" className="gap-1">
                Get Started <ArrowRight className="h-3 w-3" />
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="container mx-auto px-4 pt-24 pb-20">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="max-w-3xl mx-auto text-center"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-primary/30 bg-primary/10 text-primary text-sm font-mono mb-6">
            <span className="h-1.5 w-1.5 rounded-full bg-primary animate-pulse-glow" />
            production-ready backend generator
          </div>
          <h1 className="text-5xl md:text-7xl font-black tracking-tight mb-6 leading-[1.1] text-foreground">
            Ship your <span className="gradient-text">Supabase backend</span> in minutes
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10">
            Define your schema, roles, and features in a visual wizard. Get production-ready SQL migrations, RLS policies, edge functions, and optional React frontend — all in one ZIP.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link to="/auth?mode=signup">
              <Button size="lg" className="text-base px-8 gap-2 glow-primary">
                Start Building <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
            <Link to="/editor">
              <Button size="lg" variant="outline" className="text-base px-8 gap-2 text-foreground border-foreground/20 hover:bg-foreground/10">
                <Terminal className="h-4 w-4" /> Try Without Account
              </Button>
            </Link>
          </div>
        </motion.div>

        {/* Code Preview */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="max-w-2xl mx-auto mt-16 rounded-lg border border-border bg-card overflow-hidden"
        >
          <div className="flex items-center gap-2 px-4 py-3 border-b border-border bg-muted/50">
            <span className="h-3 w-3 rounded-full bg-destructive/60" />
            <span className="h-3 w-3 rounded-full bg-warning/60" />
            <span className="h-3 w-3 rounded-full bg-success/60" />
            <span className="ml-2 text-xs font-mono text-muted-foreground">generated-migration.sql</span>
          </div>
          <pre className="p-4 text-sm font-mono text-muted-foreground overflow-x-auto">
            <code>{`-- Generated by Supabase Factory
CREATE TABLE public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  total FLOAT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own orders"
  ON public.orders FOR SELECT
  USING (auth.uid() = user_id);`}</code>
          </pre>
        </motion.div>
      </section>

      {/* Features */}
      <section className="container mx-auto px-4 py-20">
        <h2 className="text-3xl font-bold text-center mb-12 text-foreground">Everything you need, nothing you don't</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.1 * i }}
              className="rounded-lg border border-border bg-card p-6 hover:border-primary/40 transition-colors"
            >
              <f.icon className="h-8 w-8 text-primary mb-3" />
              <h3 className="font-semibold text-lg mb-1 text-foreground">{f.title}</h3>
              <p className="text-sm text-muted-foreground">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="container mx-auto px-4 py-20">
        <div className="max-w-2xl mx-auto text-center rounded-xl border border-primary/20 bg-primary/5 p-12">
          <h2 className="text-3xl font-bold mb-4 text-foreground">Ready to build?</h2>
          <p className="text-muted-foreground mb-8">
            Stop writing boilerplate. Start shipping products.
          </p>
          <Link to="/auth?mode=signup">
            <Button size="lg" className="text-base px-8 gap-2">
              Create Your First Project <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border py-8">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
          <span className="font-mono text-foreground/60">supabase.factory</span> — built with Lovable
        </div>
      </footer>
    </div>
  );
};

export default Index;
